Repository kyma-project/istio, pull requests merged in 2022-11, with the labels that each got.

#14 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, lgtm

#22 Fix comment
  operator/pkg/lib/gatherer/gatherer.go
Labels: lgtm, size/XS

#23 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, size/XS

#8 Add issue template with DoD
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, lgtm, size/XS

#28 Allow merge with empty defaultConfig in istio Operator
  operator/api/v1alpha1/istio_merge.go
  operator/api/v1alpha1/istio_merge_test.go
Labels: area/service-mesh, size/S, lgtm

#30 Update CR descriptions
  charts/istio-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_istios.operator.kyma-project.io.yaml
  operator/api/v1alpha1/istio_structs.go
  operator/api/v1alpha1/istio_types.go
  operator/config/crd/bases/operator.kyma-project.io_istios.yaml
Labels: size/S, lgtm

#35 Add more checks for nil
  operator/api/v1alpha1/istio_merge.go
  operator/api/v1alpha1/istio_merge_test.go
Labels: lgtm, size/M
