Repository kyma-project/istio, pull requests merged in 2023-04, with the labels that each got.

#125 Add code coverage guard
  tests/integration/scripts/code-coverage-guard.sh
Labels: lgtm, size/M

#126 Istio version checking
  go.mod
  go.sum
  internal/reconciliations/istio/configuration.go
  internal/reconciliations/istio/installation_test.go
Labels: lgtm, size/L

#129 Blocking uninstall of Istio if customer resources are present
  config/rbac/role.yaml
  controllers/istio_controller.go
  docs/technical-design.md
  go.mod
  go.sum
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/istio/test/test_controlled_resource_list.yaml
  internal/resources/resource_suite_test.go
  internal/resources/resources.go
  internal/resources/resources_test.go
  internal/resources/test_resources_list.yaml
  internal/resources/test_wrong_resources_list.yaml
  internal/status/status.go
  manifests/controlled_resources_list.yaml
Labels: size/XL, lgtm

#131 Add info about Istio upgrade version checking
  docs/technical-design.md
Labels: lgtm, size/XS

#136 Create adr.md issue template
  .github/ISSUE_TEMPLATE/adr.md
Labels: size/S, lgtm

#134 Add reference to Istio CRDs in controlled_resources_list
  manifests/controlled_resources_list.yaml
Labels: lgtm, size/XS
