Repository kyma-project/istio, pull requests merged in 2023-06, with the labels that each got.

#159 Update AWS LB on Istio GW connection timeout settings via annotation
  manifests/istio-operator-template.yaml
Labels: lgtm, size/XS

#160 Restart proxies
  Dockerfile
  api/v1alpha1/istio_merge.go
  api/v1alpha1/resources.go
  api/v1alpha1/resources_test.go
  controllers/istio_controller.go
  internal/manifest/manifest.go
  internal/manifest/manifest_test.go
  internal/manifest/test/template-operator.yaml
  internal/manifest/test/test-operator.yaml
  internal/manifest/test/wrong-operator.yaml
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/proxy/sidecars.go
  internal/reconciliations/proxy/sidecars_test.go
  pkg/lib/sidecars/pods/filter.go
  pkg/lib/sidecars/pods/get.go
  pkg/lib/sidecars/pods/get_test.go
  pkg/lib/sidecars/proxy.go
  pkg/lib/sidecars/test/cases.go
  pkg/lib/sidecars/test/features/update.feature
  pkg/lib/sidecars/test/helpers/helpers.go
  pkg/lib/sidecars/test/pod_states.go
  pkg/lib/sidecars/test/test_client.go
  tests/integration/features/istio/configuration.feature
  tests/integration/features/istio/istio_installation.feature
  tests/integration/hooks.go
  tests/integration/istio_installation_scenario.go
  tests/integration/main_test.go
  tests/integration/manifests/istio_cr_template.yaml
  tests/integration/scenario.go
  tests/integration/steps/deployment.go
  tests/integration/steps/istio.go
  tests/integration/steps/istio_cr.go
  tests/integration/steps/resource.go
  tests/integration/testcontext/config.go
  tests/integration/testcontext/context.go
  tests/integration/testcontext/tags.go
  tests/integration/vars.go
Labels: size/XXL, lgtm

#163 Add script for running istio integration tests on gardener
  Makefile
  hack/ci/gardener-integration.sh
  hack/ci/jobguard.sh
Labels: lgtm, size/L

#167 Add Integration tests
  tests/integration/features/istio/istio_installation.feature
  tests/integration/hooks.go
  tests/integration/main_test.go
  tests/integration/scenario.go
  tests/integration/steps/deployment.go
  tests/integration/steps/destination_rule.go
  tests/integration/steps/resource.go
  tests/integration/testcontext/context.go
  tests/integration/testcontext/tags.go
Labels: lgtm, size/L

#166 Add html reporter for Istio module
  Makefile
  tests/integration/.gitignore
  tests/integration/main_test.go
  tests/integration/test_report.go
Labels: lgtm, size/L

#173 Increase memory and CPU limits for manager
  Makefile
  config/manager/manager.yaml
  tests/integration/features/istio/configuration.feature
Labels: size/S, lgtm

#176 Module migration
  Makefile
  PROJECT
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/istio_structs.go
  api/v1alpha2/istio_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  config/samples/operator_v1alpha1_istio.yaml
  hack/ci/gardener-integration.sh
  hack/managed-kyma-migration/migrate.sh
  hack/managed-kyma-migration/readme.md
  hack/verify_kyma_status.sh
  main.go
Labels: size/XXL, area/service-mesh, lgtm

#178 Fix for Istio uninstall when Istio already manually uninstalled
  Dockerfile
  config/manager/manager.yaml
  go.mod
  internal/reconciliations/istio/client.go
  internal/reconciliations/istio/installation.go
  internal/resources/resources.go
  internal/resources/resources_test.go
  pkg/lib/sidecars/proxy.go
  tests/integration/features/istio/production/istio_installation.feature
  tests/integration/main_test.go
  tests/integration/scenario.go
  tests/integration/steps/istio.go
Labels: lgtm, size/M

#180 Remove metrics auth
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/kustomization.yaml
Labels: size/S, lgtm

#182 Bump Istio to 1.18
  controllers/istio_controller.go
  go.mod
  go.sum
  hack/ci/Makefile
  hack/ci/jobguard.sh
  internal/reconciliations/proxy/sidecars.go
  internal/resources/resources.go
  manifests/istio-operator-template-light.yaml
  manifests/istio-operator-template.yaml
Labels: size/XL, lgtm

#191 Add security scanner config
  sec-scanners-config.yaml
Labels: size/S, lgtm

#171 Add GHA liniting
  .github/workflows/lint.yaml
Labels: size/S, lgtm

#190 Controller memory issue
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  cmd/istio-install/main.go
  config/manager/kustomization.yaml
  go.mod
  go.sum
  internal/reconciliations/istio/client.go
  tests/integration/hooks.go
  tests/integration/scenario.go
Labels: lgtm, size/L
