Repository kyma-project/istio, pull requests merged in 2023-09, with the labels that each got.

#342 add folders, remove module mentions
  README.md
  docs/contributor/01-00-installation.md
  docs/contributor/04-10-technical-design.md
  docs/contributor/04-30-ci-cd.md
  docs/user/00-20-overview-service-mesh.md
  docs/user/00-overview/00-10-overview-istio-controller.md
  docs/user/00-overview/00-20-overview-service-mesh.md
  docs/user/00-overview/00-30-overview-istio-sidecars.md
  docs/user/00-overview/00-40-overview-istio-setup.md
  docs/user/00-overview/00-50-resource-configuration.md
  docs/user/00-overview/README.md
  docs/user/00-overview/_sidebar.md
  docs/user/02-operation-guides/operations/02-20-enable-sidecar-injection.md
  docs/user/02-operation-guides/operations/_sidebar.md
  docs/user/02-operation-guides/security/02-10-ingress-egress-traffic.md
  docs/user/02-operation-guides/security/_sidebar.md
  docs/user/02-operation-guides/troubleshooting/03-10-503-no-access.md
  docs/user/02-operation-guides/troubleshooting/03-20-connection-refused.md
  docs/user/02-operation-guides/troubleshooting/03-30-istio-no-sidecar.md
  docs/user/02-operation-guides/troubleshooting/03-40-incompatible-istio-sidecar-version.md
  docs/user/02-operation-guides/troubleshooting/03-50-recovering-from-unintentional-istio-removal.md
  docs/user/02-operation-guides/troubleshooting/README.md
  docs/user/02-operation-guides/troubleshooting/_sidebar.md
  docs/user/03-technical-reference/configuration-parameters/01-10-istio-controller-parameters.md
  docs/user/03-technical-reference/configuration-parameters/_sidebar.md
  docs/user/03-technical-reference/istio-custom-resource/01-30-istio-custom-resource.md
  docs/user/03-technical-reference/istio-custom-resource/_sidebar.md
  docs/user/04-50-recovering-from-unintentional-istio-module-removal.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: lgtm, size/L

#346 Additional Istio resources into the reconciliation
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  controllers/istio_types.go
  docs/contributor/04-40-istio-resources.md
  docs/release-notes/1.0.1.md
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/reconciliations/ingress_gateway/reconciliation.go
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/istio/namespace.go
  internal/reconciliations/istio_resources/configmap_control_plane.go
  internal/reconciliations/istio_resources/configmap_control_plane.yaml
  internal/reconciliations/istio_resources/configmap_control_plane_test.go
  internal/reconciliations/istio_resources/configmap_mesh.go
  internal/reconciliations/istio_resources/configmap_mesh.yaml
  internal/reconciliations/istio_resources/configmap_mesh_test.go
  internal/reconciliations/istio_resources/configmap_performance.go
  internal/reconciliations/istio_resources/configmap_performance.yaml
  internal/reconciliations/istio_resources/configmap_performance_test.go
  internal/reconciliations/istio_resources/configmap_service.go
  internal/reconciliations/istio_resources/configmap_service.yaml
  internal/reconciliations/istio_resources/configmap_service_test.go
  internal/reconciliations/istio_resources/configmap_workload.go
  internal/reconciliations/istio_resources/configmap_workload.yaml
  internal/reconciliations/istio_resources/configmap_workload_test.go
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.go
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer_test.go
  internal/reconciliations/istio_resources/gateway_kyma.go
  internal/reconciliations/istio_resources/gateway_kyma.yaml
  internal/reconciliations/istio_resources/gateway_kyma_test.go
  internal/reconciliations/istio_resources/istio_resources.go
  internal/reconciliations/istio_resources/istio_resources_test.go
  internal/reconciliations/istio_resources/peer_authentication_mtls.go
  internal/reconciliations/istio_resources/peer_authentication_mtls.yaml
  internal/reconciliations/istio_resources/peer_authentication_mtls_test.go
  internal/reconciliations/istio_resources/reconciliation.go
  internal/reconciliations/istio_resources/virtual_service_healthz.go
  internal/reconciliations/istio_resources/virtual_service_healthz.yaml
  internal/reconciliations/istio_resources/virtual_service_healthz_test.go
  manifests/controlled_resources_list.yaml
  tests/integration/features/istio/production/main-suite/istio_configuration.feature
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/features/istio/production/main-suite/istio_resources.feature
  tests/integration/features/istio/production/main-suite/istio_sidecars.feature
  tests/integration/hooks.go
  tests/integration/main_test.go
  tests/integration/scenario.go
  tests/integration/steps/istio.go
  tests/integration/steps/istio_cr.go
  tests/integration/steps/resource.go
Labels: size/XXL, lgtm

#315 Update UI making all configuration parts not required
  config/ui-extensions/istios/form
Labels: lgtm, size/XS

#359 Update warnings and descriptions of Istio CR
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.go
  internal/reconciliations/proxy/sidecars.go
  internal/reconciliations/proxy/sidecars_test.go
  tests/integration/features/istio/production/main-suite/istio_installation.feature
Labels: lgtm, size/M

#362 Update security scanner img
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#367 Remove unneeded gateway
  tests/performance/load-testing/templates/gateway.yaml
Labels: lgtm, size/M

#363 Update local module install docs and remove unused configuration
  Makefile
  config.yaml
  docs/contributor/01-00-installation.md
  docs/contributor/04-10-technical-design.md
  docs/user/03-technical-reference/istio-custom-resource/01-30-istio-custom-resource.md
  docs/user/README.md
  hack/get_kyma_file_name.sh
  hack/local/istio/Makefile
Labels: lgtm, size/L

#372 Move a troubleshooting guide
  docs/contributor/04-10-technical-design.md
  docs/user/02-operation-guides/troubleshooting/03-60-404-on-istio-gateway.md
  docs/user/02-operation-guides/troubleshooting/_sidebar.md
Labels: lgtm, size/XS

#374 Uninstallation of istio resources test
  tests/integration/features/istio/production/main-suite/istio_resources.feature
  tests/integration/scenario.go
  tests/integration/steps/resource.go
Labels: lgtm, size/M

#371 Enable HPA for light module installation
  docs/release-notes/1.1.0.md
  manifests/istio-operator-template-light.yaml
Labels: kind/feature, lgtm, size/XS

#345 Update Makefile
  Makefile
Labels: lgtm, size/XS

#376 Add test to verify reconciliation of manually deleted resources
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/hooks.go
  tests/integration/steps/resource.go
Labels: lgtm, size/L

#378 Bump sec scanner img
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#379 Update Istio CR warning descriptions
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  docs/user/02-operation-guides/troubleshooting/03-50-recovering-from-unintentional-istio-removal.md
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  tests/integration/features/istio/production/main-suite/istio_installation.feature
Labels: size/S, lgtm

#373 Istio 1.19
  api/v1alpha1/resources_test.go
  cmd/istio-install/main.go
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  controllers/suite_test.go
  docs/release-notes/1.0.1.md
  docs/release-notes/1.1.0.md
  go.mod
  go.sum
  internal/clusterconfig/clusterconfig.go
  internal/reconciliations/istio/client.go
  internal/reconciliations/istio/installation_test.go
  pkg/lib/gatherer/gatherer_test.go
  pkg/lib/sidecars/test/helpers/helpers.go
  tests/integration/steps/deployment.go
Labels: size/XL, lgtm

#380 Release Istio module version 1.1
  VERSION
Labels: lgtm, size/XS

#381 Update release branch in Dependabot configuration
  .github/dependabot.yml
Labels: lgtm, size/XS

#382 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#383 Add Integration test to verify access between namespaces
  tests/integration/features/istio/production/main-suite/istio_connection.feature
  tests/integration/scenario.go
  tests/integration/steps/deployment.go
  tests/integration/steps/istio.go
  tests/integration/steps/nginx.go
  tests/integration/steps/nginx_config_template.yaml
  tests/integration/steps/resource.go
  tests/integration/steps/validation_requests.go
Labels: lgtm, size/L

#384 Add integration test to verify default strict PeerAuthentication
  Makefile
  tests/integration/features/istio/production/main-suite/istio_connection.feature
  tests/integration/main_test.go
  tests/integration/scenario.go
  tests/integration/steps/validation_requests.go
  tests/integration/testsupport/http_response_asserter.go
Labels: lgtm, size/M

#385 Update upgrade integration test to avoid flakiness
  tests/integration/features/istio/production/upgrade-suite/istio_upgrade.feature
  tests/integration/scenario.go
  tests/integration/steps/istio_cr.go
Labels: lgtm, size/M

#390 Update sec scanner image
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#389 Use boolean instead of string in envoy filter
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.yaml
Labels: lgtm, size/XS

#394 Fix links
  docs/contributor/04-10-technical-design.md
Labels: size/S, lgtm

#396 Update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#397 Make sure uninstall removes kyma-gateway
  tests/integration/features/istio/production/main-suite/istio_resources.feature
Labels: lgtm, size/XS
