Repository kyma-project/istio, pull requests merged in 2023-07, with the labels that each got.

#170 Initial documentation for the Istio module
  README.md
  docs/assets/controller-component-diagram.svg
  docs/assets/istio-controller-reconciliation-loop.svg
  docs/assets/istio-installation-reconciliation.svg
  docs/assets/istio-operator-overview.svg
  docs/assets/istio-whitelogo-bluebackground-framed.svg
  docs/contributor/01-00-installation.md
  docs/contributor/04-10-technical-design.md
  docs/contributor/04-20-xff-proposal.md
  docs/controller-component-diagram.svg
  docs/istio-controller-reconciliation-loop.svg
  docs/istio-installation-reconciliation.svg
  docs/istio-operator-overview.svg
  docs/user/00-10-overview-istio-controller.md
  docs/user/01-10-resource-configuration.md
  docs/user/01-20-istio-custom-resource.md
  docs/user/README.md
Labels: size/XL, lgtm

#198 Fix a link
  docs/contributor/04-10-technical-design.md
Labels: lgtm, size/XS

#189 Add release GitHub action
  .github/workflows/create-release.yaml
  Makefile
  docs/release-notes/template.md
  scripts/create_changelog.sh
  scripts/create_draft_release.sh
  scripts/publish_assets.sh
  scripts/publish_release.sh
Labels: lgtm, size/L

#199 Fix indentation in create-release.yaml
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS

#201 Lint workflow pin
  .github/workflows/lint.yaml
Labels: lgtm, size/XS

#195 Time based reconcile
  controllers/istio_controller.go
  controllers/istio_types.go
  go.mod
  go.sum
  internal/reconciliations/istio/configuration.go
  internal/reconciliations/istio/configuration_test.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  main.go
Labels: size/XL, lgtm

#203 Update pull request workflow
  .github/workflows/create-release.yaml
  .github/workflows/lint.yaml
  .github/workflows/pull-request.yaml
Labels: lgtm, size/M

#197 Synchronize Operator configuration with Kyma repository
  config/default/kustomization.yaml
  config/scheduling/kustomization.yaml
  config/scheduling/priority_class.yaml
  manifests/istio-operator-template-light.yaml
  manifests/istio-operator-template.yaml
Labels: lgtm, size/M

#205 Improve integration test reliability
  Makefile
  tests/integration/hooks.go
Labels: lgtm, size/XS

#194 Add Istio GW serviceAnnotation for Gardener clusters
  controllers/istio_controller.go
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  tests/integration/features/istio/production/istio_installation.feature
  tests/integration/hooks.go
  tests/integration/scenario.go
  tests/integration/steps/istio.go
Labels: lgtm, size/L

#207 Disallow non semantic versioned tags
  scripts/create_draft_release.sh
Labels: lgtm, size/XS

#206 Add RNs for 0.1 version
  docs/release-notes/0.1.0.md
Labels: lgtm, size/XS

#196 Istio Custom Resource status description
  api/v1alpha1/istio_types.go
  api/v1alpha2/istio_types.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  controllers/istio_controller.go
  controllers/istio_types.go
  go.mod
  go.sum
  internal/described_errors/described_errors.go
  internal/reconciliations/istio/configuration.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/proxy/sidecars.go
  internal/reconciliations/proxy/sidecars_test.go
  internal/status/status.go
  internal/status/status_test.go
  tests/integration/features/istio/production/istio_installation.feature
  tests/integration/scenario.go
  tests/integration/steps/istio_cr.go
Labels: size/XL, lgtm

#202 Update README.md with release installation guide
  README.md
  scripts/publish_assets.sh
Labels: lgtm, size/M

#212 Wait for status instead of check on release job
  .github/workflows/create-release.yaml
Labels: size/S, lgtm

#211 Wait for status instead of check on release job
  .github/workflows/create-release.yaml
Labels: size/S, lgtm

#210 Kubernetes compatibility GHA
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/verify-commit-pins.yaml
  internal/reconciliations/istio/installation.go
Labels: lgtm, size/M

#204 Reconcile interval documentation
  docs/user/01-10-resource-configuration.md
  docs/user/01-30-istio-manager.md
Labels: size/S, lgtm

#215 Update dependabot Docker config
  .github/dependabot.yml
Labels: lgtm, size/XS

#209 Warning status
  api/v1alpha1/istio_types.go
  api/v1alpha2/istio_types.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  docs/user/00-10-overview-istio-controller.md
  docs/user/01-20-istio-custom-resource.md
  internal/described_errors/described_errors.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  internal/status/status.go
  internal/status/status_test.go
  tests/integration/features/istio/production/istio_installation.feature
Labels: lgtm, size/M

#224 Create release notes for 0.2.0
  docs/release-notes/0.2.0.md
Labels: lgtm, size/XS

#227 Update dependabot.yml for release 0.2
  .github/dependabot.yml
Labels: lgtm, size/M

#223 Check that builds end in success
  .github/workflows/create-release.yaml
  .github/workflows/pull-integration.yaml
Labels: size/S, lgtm

#237 Run PR workflow on release branches
  .github/workflows/pull-request.yaml
Labels: lgtm, size/XS

#222 GitHub Actions cache build on main branch
  .github/workflows/main-cache.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/verify-commit-pins.yaml
Labels: size/S, lgtm

#236 Update dependencies
  go.mod
  go.sum
Labels: lgtm, size/M

#238 Fix build-cache job config
  .github/workflows/main-cache.yaml
Labels: lgtm, size/XS

#239 Update mergo module URL to fix dependabot error
  go.mod
  go.sum
  internal/clusterconfig/clusterconfig.go
Labels: size/S, lgtm

#208 Restart Istio GW on changes of numTrustedProxies configuration
  .github/workflows/pull-integration.yaml
  docs/contributor/04-10-technical-design.md
  internal/reconciliations/istio/configuration.go
  internal/reconciliations/istio/configuration_test.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  pkg/lib/annotations/annotations.go
  pkg/lib/annotations/annotations_test.go
  pkg/lib/common/annotations_test.go
  pkg/lib/sidecars/restart/rollout_action.go
  tests/integration/features/istio/production/configuration.feature
  tests/integration/hooks.go
  tests/integration/main_test.go
  tests/integration/scenario.go
  tests/integration/steps/deployment.go
  tests/integration/steps/istio.go
  tests/integration/steps/validation_requests.go
  tests/integration/testsupport/gardener.go
  tests/integration/testsupport/http_client.go
  tests/integration/testsupport/http_response_asserter.go
Labels: size/XXL, lgtm

#240 Add _sidebar.md
  docs/user/01-10-istio-controller-parameters.md
  docs/user/01-30-resource-configuration.md
  docs/user/_sidebar.md
Labels: lgtm, size/XS

#246 Fix Istio install error logging in child process
  cmd/istio-install/main.go
Labels: lgtm, size/XS

#249 [release/0.2] Bump istio to 1.18.1
  controllers/istio_controller.go
  docs/release-notes/0.2.1.md
  go.mod
  go.sum
  sec-scanners-config.yaml
Labels: lgtm, size/M

#250 Bump istio to 1.18.1
  controllers/istio_controller.go
  docs/release-notes/0.2.1.md
  go.mod
  go.sum
  sec-scanners-config.yaml
Labels: size/S, lgtm

#251 Change the size of headings
  docs/user/01-10-istio-controller-parameters.md
Labels: lgtm, size/XS

#248 Cleanup MWC on installation failure
  docs/release-notes/1.0.0.md
  go.mod
  go.sum
  internal/reconciliations/istio/installation.go
  internal/webhooks/webhooks.go
  internal/webhooks/webhooks_test.go
Labels: lgtm, size/L

#254 Enable bootstrap XDS agent in Istio module
  manifests/istio-operator-template-light.yaml
  manifests/istio-operator-template.yaml
Labels: kind/feature, area/service-mesh, lgtm, size/XS

#253 Fix object modified errors
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  controllers/istio_types.go
  controllers/status.go
  controllers/status_test.go
  controllers/suite_test.go
  internal/reconciliations/istio/client.go
  internal/reconciliations/istio/configuration.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/proxy/sidecars.go
  internal/reconciliations/proxy/sidecars_test.go
  internal/status/status.go
  internal/status/status_test.go
  tests/integration/features/istio/production/istio_installation.feature
Labels: size/XXL, lgtm

#270 Revert ResourceQuota due to some issues
  config/default/kustomization.yaml
  config/resourcequota/kustomization.yaml
  config/resourcequota/resource_quota_count.yaml
  docs/contributor/04-10-technical-design.md
  docs/contributor/04-20-xff-proposal.md
  tests/integration/features/istio/evaluation/istio_installation_demo.feature
  tests/integration/features/istio/production/configuration.feature
  tests/integration/features/istio/production/istio_installation.feature
  tests/integration/scenario.go
  tests/integration/steps/istio_cr.go
  tests/integration/steps/resource.go
Labels: lgtm, size/M

#273 We do not reconcile newer Istio CRs, only the oldest one
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  docs/contributor/04-10-technical-design.md
  docs/contributor/04-20-xff-proposal.md
  tests/integration/features/istio/production/istio_installation.feature
  tests/integration/hooks.go
  tests/integration/steps/istio_cr.go
  tests/integration/testcontext/context.go
Labels: lgtm, size/L

#214 Upgrade test
  .github/workflows/pull-integration.yaml
  Makefile
  go.sum
  tests/integration/.gitignore
  tests/integration/features/istio/production/main-suite/configuration.feature
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/features/istio/production/upgrade-suite/istio_upgrade.feature
  tests/integration/main_test.go
  tests/integration/pkg/manifestprocessor/processor.go
  tests/integration/scenario.go
  tests/integration/scripts/deploy-latest-release-to-cluster.sh
  tests/integration/steps/deployment.go
  tests/integration/steps/operator.go
  tests/integration/steps/resource.go
  tests/integration/test_report.go
Labels: size/XL, lgtm

#277 Istio resources technical design
  docs/assets/istio-controller-reconciliation-loop.svg
  docs/contributor/04-10-technical-design.md
Labels: size/S, lgtm

#279 Update istio version to 1.18.2
  controllers/istio_controller.go
  docs/release-notes/1.0.0.md
  go.mod
  go.sum
  sec-scanners-config.yaml
Labels: lgtm, size/M

#283 Adjust pull-integration workflow
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request.yaml
  VERSION
Labels: size/S, lgtm

#287 Generate Istio module template for regular release channel
  Makefile
  hack/ci/Makefile
Labels: lgtm, size/XS
