Repository kyma-project/istio, pull requests merged in 2023-03, with the labels that each got.

#103 Bump dependencies
  go.mod
  go.sum
Labels: lgtm, size/M

#111 Remove sidecar after Istio uninstallation
  controllers/istio_controller.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  pkg/lib/sidecars/pods/get.go
  pkg/lib/sidecars/pods/get_test.go
  pkg/lib/sidecars/remove/remove.go
  pkg/lib/sidecars/remove/remove_test.go
  pkg/lib/sidecars/test/helpers/helpers.go
Labels: lgtm, size/L

#114 Push module template to artifacts
  hack/ci/Makefile
Labels: lgtm, size/XS

#117 Istio proxy reset version check
  Dockerfile
  Makefile
  config/manager/manager.yaml
  go.mod
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/proxy/sidecars.go
  internal/reconciliations/proxy/sidecars_test.go
  pkg/lib/gatherer/gatherer.go
  pkg/lib/gatherer/gatherer_test.go
Labels: size/XL, lgtm

#116 Use only istio in performance tests
  performance_tests/.gitignore
  performance_tests/Makefile
  performance_tests/Readme.md
  performance_tests/istio-disabled.yaml
  performance_tests/istio-enabled.yaml
  performance_tests/k6_deploy.yaml
  performance_tests/load-testing/Chart.lock
  performance_tests/load-testing/Chart.yaml
  performance_tests/load-testing/templates/apirule-allow.yaml
  performance_tests/load-testing/templates/apirule-grafana.yaml
  performance_tests/load-testing/templates/apirule-jwt-istio.yaml
  performance_tests/load-testing/templates/apirule-noop.yaml
  performance_tests/load-testing/templates/apirule-oauth2.yaml
  performance_tests/load-testing/templates/config-map.yaml
  performance_tests/load-testing/templates/function.yaml
  performance_tests/load-testing/templates/grafana-dashboard.yaml
  performance_tests/load-testing/templates/grafana-datasource.yaml
  performance_tests/load-testing/templates/httpbin.yaml
  performance_tests/load-testing/templates/k6-deployment.yaml
  performance_tests/load-testing/templates/oath2client.yaml
  performance_tests/load-testing/templates/vs-allow.yaml
  performance_tests/load-testing/templates/vs-grafana.yaml
  performance_tests/load-testing/values.yaml
  performance_tests/payload-direct.json
  performance_tests/scripts/common.js
  performance_tests/scripts/jwt-post-test.js
  performance_tests/scripts/oauth-post-test.js
  performance_tests/scripts/vars.js
  performance_tests/test.sh
Labels: size/XL, lgtm

#119 Update DoD
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, size/XS

#120 DoD
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, size/XS

#121 Remove lifecycle manager deps
  Makefile
  controllers/istio_manifest_resolver.go
  controllers/istio_types.go
  go.mod
  go.sum
  main.go
  pkg/lib/sidecars/pods/get_test.go
  pkg/lib/sidecars/test/test_client.go
Labels: size/XXL, area/service-mesh, lgtm

#118 Discover cluster flavour during istio module installation
  Makefile
  config/rbac/role.yaml
  controllers/istio_controller.go
  controllers/istio_types.go
  go.mod
  hack/local/istio/Makefile
  hack/local/istio/k3d-patches/patch-kyma.yaml
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_suite_test.go
  internal/clusterconfig/clusterconfig_test.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/manifest.go
  internal/reconciliations/istio/manifest_test.go
  manifests/default-istio-operator-k3d.yaml
  manifests/istio-operator-template.yaml
Labels: size/XL, lgtm

#122 Use kyma-project image version for Istio module
  Dockerfile
Labels: lgtm, size/XS

#123 Bump Istio client-go to 1.17.x
  controllers/istio_controller.go
  go.mod
  go.sum
Labels: size/S, lgtm
