Repository kyma-project/istio, pull requests merged in 2023-02, with the labels that each got.

#72 Update istio logo
  README.md
  docs/istio-whitelogo-bluebackground-framed.svg
Labels: lgtm, size/XS

#73 Change status "Reconciling" to "Processing"
  operator/api/v1alpha1/istio_types.go
  operator/config/crd/bases/operator.kyma-project.io_istios.yaml
  operator/controllers/istio_controller.go
Labels: size/S, lgtm

#71 Add proxy sidecars reconciliation
  operator/controllers/istio_controller.go
  operator/controllers/istio_types.go
  operator/internal/reconciliations/istio/client.go
  operator/internal/reconciliations/istio/installation.go
  operator/internal/reconciliations/proxy/sidecars.go
  operator/pkg/lib/sidecars/pods/get.go
  operator/pkg/lib/sidecars/restart/restart_test.go
  operator/pkg/lib/sidecars/restart/rollout_action.go
  operator/pkg/lib/sidecars/test/cases.go
Labels: lgtm, size/L

#78 Add StatefulSets permission to controller-manager
  operator/config/rbac/role.yaml
Labels: lgtm, size/XS

#74 Add testing pipeline
  Makefile
  operator/api/v1alpha1/merge_test.go
  operator/controllers/suite_test.go
  operator/internal/reconciliations/istio/istio_suite_test.go
  operator/internal/tests/ginkgo_reporter.go
  operator/pkg/lib/gatherer/gatherer_test.go
  operator/pkg/lib/sidecars/pods/get_test.go
  operator/pkg/lib/sidecars/restart/restart_test.go
Labels: lgtm, size/M

#79 Fix wrong usage of structured logging
  operator/internal/reconciliations/proxy/sidecars.go
Labels: lgtm, size/XS

#80 Use patch instead of an update in sidecar rollout action
  operator/pkg/lib/sidecars/restart/rollout_action.go
Labels: size/S, lgtm

#89 Replace usernames with a team name in CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/XS

#90 Uninstallation of Istio
  Makefile
  operator/Makefile
  operator/README.md
  operator/api/v1alpha1/istio_types.go
  operator/controllers/istio_controller.go
  operator/controllers/istio_manifest_resolver.go
  operator/internal/reconciliations/istio/client.go
  operator/internal/reconciliations/istio/configuration.go
  operator/internal/reconciliations/istio/installation.go
  operator/internal/reconciliations/istio/installation_test.go
  operator/internal/status/status.go
  operator/pkg/lib/gatherer/gatherer.go
Labels: size/XL, lgtm

#91 Review the operator README
  operator/README.md
Labels: lgtm, size/M

#92 Update Istio default operator manifests HPA to autoscaling/v2
  operator/manifests/default-istio-operator-cluster.yaml
  operator/manifests/default-istio-operator-k3d.yaml
Labels: size/S, lgtm

#94 Change istio-system deletion propagation
  operator/internal/reconciliations/istio/client.go
Labels: lgtm, size/XS

#93 Add Istio performance tests
  .gitignore
  Makefile
  operator/performance_tests/Readme.md
  operator/performance_tests/grafana_dashboard.json
  operator/performance_tests/k6_deploy.yaml
  operator/performance_tests/load-testing/.gitignore
  operator/performance_tests/load-testing/.helmignore
  operator/performance_tests/load-testing/Chart.lock
  operator/performance_tests/load-testing/Chart.yaml
  operator/performance_tests/load-testing/templates/_helpers.tpl
  operator/performance_tests/load-testing/templates/apirule-allow.yaml
  operator/performance_tests/load-testing/templates/apirule-grafana.yaml
  operator/performance_tests/load-testing/templates/apirule-jwt-istio.yaml
  operator/performance_tests/load-testing/templates/apirule-noop.yaml
  operator/performance_tests/load-testing/templates/apirule-oauth2.yaml
  operator/performance_tests/load-testing/templates/config-map.yaml
  operator/performance_tests/load-testing/templates/function.yaml
  operator/performance_tests/load-testing/templates/grafana-dashboard.yaml
  operator/performance_tests/load-testing/templates/grafana-datasource.yaml
  operator/performance_tests/load-testing/templates/k6.yaml
  operator/performance_tests/load-testing/templates/oath2client.yaml
  operator/performance_tests/load-testing/values.yaml
  operator/performance_tests/payload-direct.json
  operator/performance_tests/scripts/common.js
  operator/performance_tests/scripts/jwt-post-test.js
  operator/performance_tests/scripts/oauth-post-test.js
  operator/performance_tests/scripts/vars.js
  operator/performance_tests/test.sh
Labels: size/XXL, lgtm
