Repository kyma-project/istio, pull requests merged in 2023-05, with the labels that each got.

#133 Add Istio installation and uninstallation test
  Makefile
  go.mod
  go.sum
  hack/verify_kyma_status.sh
  tests/integration/features/istio/istio_installation.feature
  tests/integration/istio_instalation_scenario.go
  tests/integration/main_test.go
  tests/integration/manifests/crd_list.yaml
  tests/integration/manifests/crd_lister.go
  tests/integration/vars.go
Labels: lgtm, size/L

#142 Fix istio-manager-verify pipeline
  hack/local/istio/Makefile
Labels: lgtm, size/XS

#144 Update Istio installation guide in README
  README.md
Labels: area/service-mesh, size/S, lgtm

#139 Fix issues with performance test to make it pipeline ready
  performance_tests/Makefile
  performance_tests/load-testing/templates/vs-allow.yaml
  performance_tests/load-testing/templates/vs-grafana.yaml
Labels: lgtm, size/XS

#147 Update issue templates
  .github/ISSUE_TEMPLATE/adr.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: area/service-mesh, lgtm, size/XS

#153 Clean up istio sample
  config/samples/operator_v1alpha1_istio.yaml
Labels: lgtm, size/XS
