Repository kyma-project/istio, pull requests merged in 2023-12, with the labels that each got.

#503 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#502 Update cicd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#507 XFF tutorial
  docs/user/_sidebar.md
  docs/user/tutorials/01-00-x-forwarded-for-header.md
  docs/user/tutorials/README.md
  docs/user/tutorials/assets/01-00-num-trusted-proxies-ui.svg
Labels: lgtm, size/L, cla: yes

#511 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#512 Include istio-injection label when creating kyma-system ns
  Makefile
  README.md
Labels: lgtm, size/XS, cla: yes

#516 Set VERSION file to 1.1.3
  VERSION
  docs/release-notes/1.1.3.md
Labels: lgtm, size/XS, cla: yes

#517 Delete .github/workflows/vulnerabilities-check.yaml
  .github/workflows/vulnerabilities-check.yaml
Labels: lgtm, size/M, cla: yes

#521 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#519 Adjust Istio documentation to the new content guidelines
  README.md
  docs/contributor/01-00-installation.md
  docs/contributor/04-10-technical-design.md
  docs/contributor/04-30-ci-cd.md
  docs/release-notes/template.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/00-20-overview-service-mesh.md
  docs/user/00-30-overview-istio-sidecars.md
  docs/user/00-40-overview-istio-setup.md
  docs/user/00-50-resource-configuration.md
  docs/user/04-00-istio-custom-resource.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/operation-guides/02-10-check-if-sidecar-injection-is-enabled.md
  docs/user/operation-guides/02-20-enable-sidecar-injection.md
  docs/user/operation-guides/02-30-enable-istio-access-logs.md
  docs/user/operation-guides/README.md
  docs/user/technical-reference/05-00-istio-controller-parameters.md
  docs/user/technical-reference/README.md
  docs/user/troubleshooting/03-10-503-no-access.md
  docs/user/troubleshooting/03-20-connection-refused.md
  docs/user/troubleshooting/03-30-istio-no-sidecar.md
  docs/user/troubleshooting/03-40-incompatible-istio-sidecar-version.md
  docs/user/troubleshooting/03-50-recovering-from-unintentional-istio-removal.md
  docs/user/troubleshooting/03-60-404-on-istio-gateway.md
  docs/user/troubleshooting/README.md
  docs/user/tutorials/01-00-x-forwarded-for-header.md
  hack/managed-kyma-migration/readme.md
  tests/performance/Readme.md
Labels: lgtm, size/L, cla: yes

#523 Bump Go version to 1.21.5 and use newer alpine image
  Dockerfile
Labels: lgtm, size/XS, cla: yes

#524 Remove module template and LM testing leftovers
  .env
  .github/workflows/create-release.yaml
  Makefile
  hack/ci/Makefile
  hack/local/Makefile
  hack/local/busola/Makefile
  hack/local/busola/k3d-patches/busola-extensibility.yaml
  hack/local/busola/k3d-patches/busola-kyma-extension.yaml
  hack/local/istio/Makefile
  hack/local/istio/k3d-patches/patch-k3d-lifecycle-manager-clusterrole.yaml
Labels: lgtm, size/L, cla: yes

#525 Remove module template related docs
  docs/contributor/01-00-installation.md
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#533 Update XFF header documentation
  docs/user/00-10-overview-istio-controller.md
Labels: size/S, lgtm, cla: yes

#535 Update Dependabot release target branch
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes
