Repository kyma-project/istio, pull requests merged in 2023-10, with the labels that each got.

#399 update sec scanner img
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#400 Update action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
Labels: lgtm, size/XS

#416 update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#418 Bump Istio to 1.19.3
  controllers/istio_controller.go
  go.mod
  go.sum
  main.go
Labels: lgtm, size/L

#311 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: lgtm, size/L

#427 updace sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#430 Bump Istio to 1.19.3 (#418)
  controllers/istio_controller.go
  go.mod
  go.sum
  main.go
Labels: lgtm, size/L

#435 Use boolean instead of string in envoy filter (#389)
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.yaml
Labels: lgtm, size/XS

#434 Add 1.1.1 release notes and update version file
  VERSION
  docs/release-notes/1.1.1.md
Labels: lgtm, size/XS

#438 Istio module manifests should not deploy kyma-system
  Makefile
  README.md
  config/manager/manager.yaml
Labels: lgtm, size/M

#445 Create vulnerabilities-check.yaml
  .github/workflows/vulnerabilities-check.yaml
Labels: lgtm, size/M

#447 update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS
