Repository kyma-project/istio, pull requests merged in 2023-08, with the labels that each got.

#291 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#292 Coverage guard run on PR
  .github/workflows/pull-request.yaml
Labels: lgtm, size/XS

#295 Rns for istio 1.0.0
  docs/release-notes/1.0.0.md
Labels: lgtm, size/XS

#290 Busola UI extension for Istio operator spec
  config/default/kustomization.yaml
  config/ui-extensions/istios/details
  config/ui-extensions/istios/form
  config/ui-extensions/istios/general
  config/ui-extensions/istios/kustomization.yaml
  config/ui-extensions/istios/list
  config/ui-extensions/istios/translations
  config/ui-extensions/kustomization.yaml
  tests/integration/pkg/manifestprocessor/processor.go
  tests/integration/steps/operator.go
Labels: lgtm, size/L

#297 Fix pipelines
  .github/actions/slack-notification-failed-workflow/action.yaml
  .github/actions/upgrade-integration-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration.yaml
  tests/integration/main_test.go
Labels: size/S, lgtm

#298 Release Istio module version 1.0
  .github/workflows/pull-integration.yaml
  VERSION
  tests/integration/main_test.go
Labels: lgtm, size/XS

#300 Fix busola UI typos
  config/ui-extensions/istios/translations
Labels: lgtm, size/XS

#304 Build module for fast channel as well
  .gitignore
  Makefile
  docs/contributor/01-00-installation.md
  hack/ci/Makefile
  hack/local/istio/Makefile
Labels: lgtm, size/M

#314 Bump istio manager img in security scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#321 Add status badge error description to Istio UI extension
  config/ui-extensions/istios/details
  config/ui-extensions/istios/list
Labels: size/S, lgtm

#322 Fix perf tests script running nightly Istio CR in kyma-system
  hack/ci/gardener-perf-test.sh
Labels: lgtm, size/XS

#313 Add cicd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M

#301 Copy documentation from Kyma to the module's repo
  docs/assets/istio-installation-reconciliation.svg
  docs/assets/sidecar-analysis.sh
  docs/contributor/04-10-technical-design.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/00-20-overview-service-mesh.md
  docs/user/00-30-overview-istio-sidecars.md
  docs/user/00-40-overview-istio-setup.md
  docs/user/01-20-istio-custom-resource.md
  docs/user/01-40-ingress-egress-traffic.md
  docs/user/01-50-enable-sidecar-injection.md
  docs/user/04-10-503-no-access.md
  docs/user/04-20-connection-refused.md
  docs/user/04-30-istio-no-sidecar.md
  docs/user/04-40-incompatible-istio-sidecar-version.md
  docs/user/04-50-recovering-from-unintentional-istio-module-removal.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: lgtm, size/L

#324 Bump img for security scans
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#332 Fix error badge
  Makefile
  config/ui-extensions/istios/details
  config/ui-extensions/istios/list
Labels: size/S, lgtm

#344 Update img for sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#351 Update release branch in dependabot config and add k8s dependency group
  .github/dependabot.yml
Labels: size/S, lgtm

#355 Ignore controller runtime updates in dependabot
  .github/dependabot.yml
Labels: lgtm, size/XS

#357 Exclude test files from sec scans
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#333 Create 04-60-404-on-istio-gateway.md
  docs/user/04-60-404-on-istio-gateway.md
Labels: size/S, lgtm
