Repository kyma-project/istio, pull requests merged in 2023-11, with the labels that each got.

#449 Don't create kyma gateway
  controllers/istio_controller.go
  docs/contributor/04-10-technical-design.md
  docs/contributor/04-40-istio-resources.md
  internal/reconciliations/istio_resources/gateway_kyma.go
  internal/reconciliations/istio_resources/gateway_kyma.yaml
  internal/reconciliations/istio_resources/gateway_kyma_test.go
  internal/reconciliations/istio_resources/istio_resources_test.go
  internal/reconciliations/istio_resources/virtual_service_healthz.go
  internal/reconciliations/istio_resources/virtual_service_healthz.yaml
  internal/reconciliations/istio_resources/virtual_service_healthz_test.go
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/features/istio/production/main-suite/istio_resources.feature
Labels: lgtm, size/L

#451 Don't create kyma gateway
  VERSION
  controllers/istio_controller.go
  docs/contributor/04-10-technical-design.md
  docs/contributor/04-40-istio-resources.md
  docs/release-notes/1.1.2.md
  internal/reconciliations/istio_resources/gateway_kyma.go
  internal/reconciliations/istio_resources/gateway_kyma.yaml
  internal/reconciliations/istio_resources/gateway_kyma_test.go
  internal/reconciliations/istio_resources/istio_resources_test.go
  internal/reconciliations/istio_resources/virtual_service_healthz.go
  internal/reconciliations/istio_resources/virtual_service_healthz.yaml
  internal/reconciliations/istio_resources/virtual_service_healthz_test.go
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/features/istio/production/main-suite/istio_resources.feature
Labels: lgtm, size/L

#443 Add Client IP in XFF header for AWS
  Makefile
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  controllers/suite_test.go
  docs/user/00-overview/00-10-overview-istio-controller.md
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/gardener_shoot_info.go
  internal/clusterconfig/hyperscaler.go
  internal/clusterconfig/hyperscaler_test.go
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/istio/namespace.go
  internal/reconciliations/istio_resources/configmap_control_plane.go
  internal/reconciliations/istio_resources/configmap_control_plane_test.go
  internal/reconciliations/istio_resources/configmap_mesh.go
  internal/reconciliations/istio_resources/configmap_mesh_test.go
  internal/reconciliations/istio_resources/configmap_performance.go
  internal/reconciliations/istio_resources/configmap_performance_test.go
  internal/reconciliations/istio_resources/configmap_service.go
  internal/reconciliations/istio_resources/configmap_service_test.go
  internal/reconciliations/istio_resources/configmap_workload.go
  internal/reconciliations/istio_resources/configmap_workload_test.go
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.go
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer_test.go
  internal/reconciliations/istio_resources/istio_resources_test.go
  internal/reconciliations/istio_resources/peer_authentication_mtls.go
  internal/reconciliations/istio_resources/peer_authentication_mtls_test.go
  internal/reconciliations/istio_resources/proxy_protocol_envoy_filter.go
  internal/reconciliations/istio_resources/proxy_protocol_envoy_filter.yaml
  internal/reconciliations/istio_resources/reconciliation.go
  internal/reconciliations/istio_resources/reconciliation_test.go
  internal/resources/apply.go
  internal/resources/apply_test.go
  internal/resources/disclaimer_annotation.go
  internal/resources/disclaimer_annotation_test.go
  internal/resources/istio_resources_finder.go
  internal/resources/istio_resources_finder_test.go
  internal/resources/test_files/resource_with_data.yaml
  internal/resources/test_files/resource_with_spec.yaml
  internal/resources/test_files/test_resources_list.yaml
  internal/resources/test_files/test_wrong_resources_list.yaml
  manifests/controlled_resources_list.yaml
  manifests/istio-operator-template-light.yaml
  manifests/istio-operator-template.yaml
  tests/integration/features/istio/production/aws-suite/xff_header.feature
  tests/integration/main_test.go
  tests/integration/pkg/ip/loadbalancer.go
  tests/integration/pkg/ip/public_ip.go
  tests/integration/scenario.go
  tests/integration/steps/validation_requests.go
  tests/integration/steps/x_forwarded_for_validation.go
Labels: size/XXL, lgtm

#454 Integration tests gardener
  tests/integration/scripts/integration-test-aws-specific.sh
  tests/integration/scripts/integration-test-gardener.sh
  tests/integration/scripts/jobguard.sh
  tests/integration/scripts/provison-gardener.sh
Labels: lgtm, size/L

#456 update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#463 Remove vulnerability check from PRs
  .github/workflows/vulnerabilities-check.yaml
Labels: lgtm, size/XS

#465 update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#473 Update go version
  .github/workflows/vulnerabilities-check.yaml
  go.mod
Labels: lgtm, size/XS

#474 Ignore istio dependencies in dependabot config
  .github/dependabot.yml
Labels: lgtm, size/XS

#457 Update feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, size/XS

#478 Move the Istio logs tutorial from Kyma
  docs/user/00-overview/_sidebar.md
  docs/user/02-operation-guides/operations/02-30-enable-istio-access-logs.md
  docs/user/02-operation-guides/operations/_sidebar.md
  docs/user/02-operation-guides/security/_sidebar.md
  docs/user/03-technical-reference/configuration-parameters/_sidebar.md
Labels: lgtm, size/M

#485 Remove Grafana Dashboards ConfigMaps
  internal/reconciliations/istio_resources/configmap_control_plane.go
  internal/reconciliations/istio_resources/configmap_control_plane.yaml
  internal/reconciliations/istio_resources/configmap_control_plane_test.go
  internal/reconciliations/istio_resources/configmap_mesh.go
  internal/reconciliations/istio_resources/configmap_mesh.yaml
  internal/reconciliations/istio_resources/configmap_mesh_test.go
  internal/reconciliations/istio_resources/configmap_performance.go
  internal/reconciliations/istio_resources/configmap_performance.yaml
  internal/reconciliations/istio_resources/configmap_performance_test.go
  internal/reconciliations/istio_resources/configmap_service.go
  internal/reconciliations/istio_resources/configmap_service.yaml
  internal/reconciliations/istio_resources/configmap_service_test.go
  internal/reconciliations/istio_resources/configmap_workload.go
  internal/reconciliations/istio_resources/configmap_workload.yaml
  internal/reconciliations/istio_resources/configmap_workload_test.go
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.go
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer_test.go
  internal/reconciliations/istio_resources/peer_authentication_mtls.go
  internal/reconciliations/istio_resources/peer_authentication_mtls_test.go
  internal/reconciliations/istio_resources/proxy_protocol_envoy_filter.go
  internal/reconciliations/istio_resources/reconciliation.go
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/features/istio/production/main-suite/istio_resources.feature
Labels: size/XXL, lgtm

#486 Missing integration test script on release branch
  tests/integration/scripts/integration-test-aws-specific.sh
Labels: lgtm, size/XS

#483 Bump Istio to 1.20
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-integration-test/action.yaml
  .github/workflows/main-cache.yaml
  .github/workflows/pull-request.yaml
  cmd/istio-install/main.go
  controllers/istio_controller.go
  docs/release-notes/1.2.0.md
  go.mod
  go.sum
  internal/reconciliations/istio/client.go
  internal/reconciliations/istio/installation_test.go
  manifests/istio-operator-template-light.yaml
  manifests/istio-operator-template.yaml
Labels: lgtm, size/L

#488 Fix sidebars after removals
  docs/user/00-overview/_sidebar.md
  docs/user/02-operation-guides/operations/_sidebar.md
  docs/user/02-operation-guides/security/_sidebar.md
  docs/user/03-technical-reference/configuration-parameters/_sidebar.md
  docs/user/03-technical-reference/istio-custom-resource/_sidebar.md
Labels: size/S, lgtm, do-not-merge/missing-docs-review

#491 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#492 Fix upgrade test tags
  tests/integration/scripts/deploy-latest-release-to-cluster.sh
Labels: size/S, lgtm

#493 Exclude main
  .github/workflows/main-integration.yaml
Labels: lgtm, size/XS

#494 update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#490 [Release 1.2.0] Update VERSION and security scanner config
  VERSION
  sec-scanners-config.yaml
  tests/integration/scripts/deploy-latest-release-to-cluster.sh
Labels: size/S, lgtm

#455 Add UI instructions
  docs/assets/check-istio-proxy-ports.svg
  docs/assets/delete-istio-ingressgateway-pods.svg
  docs/assets/istio-cr-delete-finalizers.svg
  docs/assets/istio-cr-warning-state.svg
  docs/assets/namespace-with-enabled-istio-sidecar.svg
  docs/assets/search-for-istio-ingress-gateway.svg
  docs/assets/sidecar-injection-toggle-deployment.svg
  docs/assets/sidecar-injection-toggle-namespace.svg
  docs/assets/view-istio-proxy-logs.svg
  docs/user/02-operation-guides/operations/02-10-check-if-sidecar-injection-is-enabled.md
  docs/user/02-operation-guides/operations/02-20-enable-sidecar-injection.md
  docs/user/02-operation-guides/security/02-10-ingress-egress-traffic.md
  docs/user/02-operation-guides/troubleshooting/03-10-503-no-access.md
  docs/user/02-operation-guides/troubleshooting/03-30-istio-no-sidecar.md
  docs/user/02-operation-guides/troubleshooting/03-40-incompatible-istio-sidecar-version.md
  docs/user/02-operation-guides/troubleshooting/03-50-recovering-from-unintentional-istio-removal.md
Labels: lgtm, size/L, cla: yes

#495 Update technical design
  docs/assets/controller-component-diagram.svg
  docs/assets/istio-controller-reconciliation-loop.svg
  docs/assets/istio-installation-reconciliation.svg
  docs/assets/istio-operator-overview.svg
  docs/contributor/04-10-technical-design.md
  docs/contributor/04-20-xff-proposal.md
  docs/user/03-technical-reference/istio-custom-resource/01-30-istio-custom-resource.md
Labels: lgtm, size/L, cla: yes
