Repository kyma-project/istio, pull requests merged in 2024-07, with the labels that each got.

#909 Add Pre-Merge Checklist to the PR template
  .github/pull-request-template.md
Labels: lgtm, size/XS, cla: yes

#911 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#907 Add information about Istio Ingressgateway scaling
  tests/performance/Readme.md
Labels: size/S, lgtm, cla: yes

#910 Error signal when performance tests failed to run
  hack/ci/gardener-perf-test.sh
Labels: lgtm, size/XS, cla: yes

#916 Increase main testsuite timeout to avoid failing job
  Makefile
Labels: lgtm, size/XS, cla: yes

#912 Istio 1.22.2
  README.md
  docs/release-notes/1.8.1.md
  docs/user/README.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#917 Istio 1.22.2 (#912)
  README.md
  VERSION
  docs/release-notes/1.8.1.md
  docs/user/README.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#918 Ignore k3d import for main build
  .github/actions/integration-test/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-integration-test/action.yaml
Labels: size/S, lgtm, cla: yes

#919 Trigger integration tests on main
  VERSION
Labels: lgtm, size/XS, cla: yes

#920 Add missing links to CI/CD docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/XS, cla: yes

#923 Rename check-build-image job in PR workflow
  .github/workflows/pull-request.yaml
Labels: lgtm, size/XS, cla: yes

#924 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#929 bug: fix incorrect prefix for image
  .github/workflows/ui-tests-periodic.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#928 Adapt performance test
  hack/ci/gardener-perf-test.sh
  tests/performance/Makefile
  tests/performance/istio-max-replicas.yaml
  tests/performance/load-testing/templates/httpbin.yaml
Labels: lgtm, size/M, cla: yes

#932 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#933 bug: add timeout to kubectl wait for service ip
  tests/performance/Makefile
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#935 bug: add scripts/get_latest_build_sha.sh use to perf test
  .github/workflows/performance-test.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#936 Use stable version for istio telemetry API in docs
  docs/user/operation-guides/02-30-enable-istio-access-logs.md
Labels: size/S, lgtm, cla: yes

#926 Proxy reset with pagination and reconciliation requeue
  api/v1alpha2/conditions.go
  api/v1alpha2/istio_types.go
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  docs/contributor/04-10-technical-design.md
  docs/contributor/adr/0002-istio-cr-status-improvements.md
  docs/release-notes/1.9.0.md
  docs/user/00-10-overview-istio-controller.md
  internal/clusterconfig/clusterconfig_test.go
  internal/compatibility/proxy_restart.go
  internal/compatibility/proxy_restart_test.go
  internal/filter/predicate.go
  internal/restarter/ingress_gateway.go
  internal/restarter/ingress_gateway_test.go
  internal/restarter/restart.go
  internal/restarter/restart_test.go
  internal/restarter/sidecars.go
  internal/restarter/sidecars_test.go
  main.go
  pkg/lib/ingressgateway/ingressgateway_test.go
  pkg/lib/sidecars/pods/filter.go
  pkg/lib/sidecars/pods/filter_test.go
  pkg/lib/sidecars/pods/get.go
  pkg/lib/sidecars/pods/get_test.go
  pkg/lib/sidecars/proxy.go
  pkg/lib/sidecars/test/cases.go
  pkg/lib/sidecars/test/features/update.feature
  pkg/lib/sidecars/test/helpers/helpers.go
  pkg/lib/sidecars/test/test_client.go
Labels: size/XL, lgtm, cla: yes

#938 Security scanner config update
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#943 Use correct commit for PR image build
  .github/workflows/pull-integration-gardener.yaml
Labels: lgtm, size/XS, cla: yes

#941 chore: bump golang image to 1.22.5 in Dockerfile
  Dockerfile
  go.mod
  go.sum
Labels: area/service-mesh, lgtm, size/M, tide/merge-method-merge, kind/chore, cla: yes

#930 Rate limit technical design
  docs/assets/istio-operator-overview-ratelimit.svg
  docs/contributor/adr/0008-rate-limit.md
Labels: lgtm, size/L, cla: yes

#950 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#954 Change enable and disable to add and delete in the istio repo
  docs/user/tutorials/01-00-x-forwarded-for-header.md
  docs/user/tutorials/01-10-external-authorization-provider.md
  hack/managed-kyma-migration/readme.md
Labels: lgtm, size/XS, cla: yes

#955 Fix schedule configuration for update sec-scanners-config.yaml
  .github/workflows/update-sec-scanner.yaml
Labels: lgtm, size/XS, cla: yes

#956 bug: fix fetching origin in update-sec-scanner.yaml
  .github/workflows/update-sec-scanner.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#945 Update Istio version to 1.22.3
  README.md
  docs/release-notes/1.9.0.md
  docs/user/README.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#958 Bump Istio to 1.22.3 and update version
  README.md
  VERSION
  docs/release-notes/1.8.2.md
  docs/release-notes/1.9.0.md
  docs/user/README.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes
