Repository kyma-project/istio, pull requests merged in 2024-10, with the labels that each got.

#1051 Update CI/CD docs
  .github/workflows/performance-test.yaml
  .github/workflows/ui-tests-periodic.yaml
  docs/contributor/04-30-ci-cd.md
Labels: size/S, lgtm, cla: yes

#1048 Include breaking changes in release notes
  docs/release-notes/1.9.0.md
Labels: lgtm, size/XS, cla: yes

#1050 feat: Add proper categories for CRDs
  api/v1alpha1/istio_types.go
  api/v1alpha2/istio_types.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
Labels: lgtm, size/XS, cla: yes

#1053 Update Istio bump template
  .github/ISSUE_TEMPLATE/istio_update.md
Labels: lgtm, size/XS, cla: yes

#1052 Remove sec scanner config from ignored files on rel pr pipeline
  .github/workflows/pull-request-release.yaml
Labels: lgtm, size/XS, cla: yes

#1054 Release 1.9 version bump
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1057 Fix permissions for create release workflow
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, cla: yes

#1056 Fix broken main scheduled tests
  .github/actions/get-latest-sha/action.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/ui-tests-periodic.yaml
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#1059 Cherry pick fix of create rel workflow permissions
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, cla: yes

#1058 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1060 Update CI/CD docs with latest links
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/XS, cla: yes

#1049 Increase certificate key size for mesh-to-mesh communication
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
Labels: lgtm, size/XS, cla: yes

#1061 Update Dependabot configuration
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1062 Remove Istio version v1alpha1
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/istio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  docs/release-notes/1.10.0.md
  docs/user/troubleshooting/03-50-recovering-from-unintentional-istio-removal.md
  docs/user/tutorials/01-10-external-authorization-provider.md
  internal/clusterconfig/clusterconfig_test.go
  internal/resources/disclaimer_annotation_test.go
  internal/webhooks/webhooks_test.go
  main.go
  pkg/lib/gatherer/gatherer.go
  pkg/lib/gatherer/gatherer_test.go
  pkg/lib/sidecars/pods/get_test.go
Labels: size/XXL, lgtm, cla: yes

#1073 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1074 Add new workflow for image syncer
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-gardener.yaml
  .github/workflows/pull-request-release.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/sync-external-images.yaml
  docs/contributor/04-30-ci-cd.md
  external-images.yaml
Labels: lgtm, size/M, cla: yes

#1075 Add link for sync-external-images to CI/CD docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/XS, cla: yes

#1071 Remove support for disable external name alias annotation
  api/v1alpha2/compatibility_mode_test.go
  api/v1alpha2/istio_merge.go
  api/v1alpha2/merge_test.go
  docs/release-notes/1.10.0.md
  docs/user/04-00-istio-custom-resource.md
  internal/istiooperator/merge_experimental_test.go
  pkg/lib/annotations/annotations.go
Labels: lgtm, size/L, do-not-merge/hold, cla: yes

#1078 chore: merge gitleaks job into pull-request.yaml
  .github/workflows/pull-gitleaks.yaml
  .github/workflows/pull-request.yaml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1079 docs: update ci/cd docs
  docs/contributor/04-30-ci-cd.md
Labels: area/documentation, lgtm, size/XS, kind/chore, cla: yes

#1081 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, cla: yes

#1080 Refactor main test suite into more granular ones
  .github/actions/integration-test/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-gardener-release.yaml
  .github/workflows/pull-integration-gardener.yaml
  .github/workflows/pull-integration-release.yaml
  .github/workflows/pull-integration.yaml
  Makefile
  hack/ci/gardener-integration.sh
  hack/ci/shoot_aws.yaml
  hack/ci/shoot_gcp.yaml
  tests/integration/features/aws-suite/xff_header.feature
  tests/integration/features/configuration-suite/configuration.feature
  tests/integration/features/evaluation-suite/install.feature
  tests/integration/features/gcp-suite/xff_header.feature
  tests/integration/features/installation-suite/install.feature
  tests/integration/features/installation-suite/uninstall.feature
  tests/integration/features/istio/production/main-suite/istio_resources.feature
  tests/integration/features/istio/production/main-suite/istio_sidecars.feature
  tests/integration/features/mesh-communication-suite/mesh_communication.feature
  tests/integration/features/observability-suite/observability.feature
  tests/integration/features/upgrade-suite/istio_upgrade.feature
  tests/integration/main_test.go
Labels: lgtm, size/L, cla: yes

#1084 Update CI/CD docs links and description for integration tests
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#1076 Add `istio-system` namespace to module manifest
  Makefile
  README.md
  config/namespace/istio_system_namespace.yaml
  docs/release-notes/1.10.0.md
Labels: size/S, lgtm, cla: yes

#1083 Add CA certs plug-in guide
  docs/user/troubleshooting/03-90-istio-cert-unknown.md
Labels: size/S, lgtm, cla: yes

#1090 Update Istio upgrade issue template
  .github/ISSUE_TEMPLATE/istio_update.md
Labels: lgtm, size/XS, cla: yes

#1092 Update VERSION and sec-scanners
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1089 Remove plutono from performance tests
  hack/ci/gardener-perf-test.sh
  tests/performance/Makefile
Labels: size/S, lgtm, cla: yes

#1093 Fix performance tests
  .github/workflows/performance-test.yaml
  tests/performance/load-testing/Chart.lock
  tests/performance/load-testing/Chart.yaml
  tests/performance/load-testing/templates/vs-grafana.yaml
  tests/performance/load-testing/values.yaml
Labels: lgtm, size/M, cla: yes

#1094 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#999 Prepare Istio documentation for migration to Help Portal
  docs/assets/istio-controller-overview-user.svg
  docs/assets/istio-cr-delete-finalizers.svg
  docs/assets/istio-cr-warning-state.svg
  docs/assets/sidecar-analysis.sh
  docs/assets/sidecar-injection-toggle-deployment.svg
  docs/assets/sidecar-injection-toggle-namespace.svg
  docs/user/00-00-istio-sidecar-proxies.md
  docs/user/00-10-istio-version.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/00-15-overview-istio-setup.md
  docs/user/00-20-overview-service-mesh.md
  docs/user/00-30-overview-istio-sidecars.md
  docs/user/00-40-overview-istio-setup.md
  docs/user/00-50-resource-configuration.md
  docs/user/04-00-istio-custom-resource.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/operation-guides/02-10-check-if-sidecar-injection-is-enabled.md
  docs/user/operation-guides/02-20-enable-sidecar-injection.md
  docs/user/operation-guides/README.md
  docs/user/technical-reference/05-00-istio-controller-parameters.md
  docs/user/technical-reference/README.md
  docs/user/troubleshooting/03-00-istio-basic-diagnostics.md
  docs/user/troubleshooting/03-00-network-connectivity.md
  docs/user/troubleshooting/03-10-503-no-access.md
  docs/user/troubleshooting/03-20-connection-refused.md
  docs/user/troubleshooting/03-30-istio-no-sidecar.md
  docs/user/troubleshooting/03-40-incompatible-istio-sidecar-version.md
  docs/user/troubleshooting/03-50-recovering-from-unintentional-istio-removal.md
  docs/user/troubleshooting/03-60-404-on-istio-gateway.md
  docs/user/troubleshooting/03-70-reconciliation-fails-on-istio-install.md
  docs/user/troubleshooting/03-80-cannot-connect-to-hana-db.md
  docs/user/troubleshooting/README.md
  docs/user/tutorials/01-00-x-forwarded-for-header.md
  docs/user/tutorials/01-10-external-authorization-provider.md
  docs/user/tutorials/01-20-expose-httbin-gateway-api.md
  docs/user/tutorials/01-30-expose-tcp-gateway-api.md
  docs/user/tutorials/01-40-enable-sidecar-injection.md
  docs/user/tutorials/01-45-enable-istio-access-logs.md
  docs/user/tutorials/README.md
Labels: size/XXL, lgtm, cla: yes

#1091 Create ADR for Istio `egressGateway` component
  docs/contributor/adr/0009-egress-gateway.md
Labels: lgtm, size/M, cla: yes

#1099 Use the correct titles in the sidebar
  docs/user/_sidebar.md
  docs/user/troubleshooting/03-10-503-no-access.md
  docs/user/troubleshooting/03-40-incompatible-istio-sidecar-version.md
  docs/user/troubleshooting/03-60-404-on-istio-gateway.md
  docs/user/troubleshooting/03-90-istio-cert-unknown.md
  docs/user/tutorials/01-10-external-authorization-provider.md
  docs/user/tutorials/01-20-expose-httbin-gateway-api.md
  docs/user/tutorials/01-30-expose-tcp-gateway-api.md
  docs/user/tutorials/01-40-enable-sidecar-injection.md
  docs/user/tutorials/01-45-enable-istio-access-logs.md
Labels: size/S, lgtm, cla: yes

#1100 Fix broken links
  README.md
  docs/release-notes/1.3.0.md
  docs/release-notes/1.4.0.md
  docs/release-notes/1.9.0.md
Labels: lgtm, size/M, cla: yes
