Repository kyma-project/istio, pull requests merged in 2024-05, with the labels that each got.

#791 workflows: add experimental tagging (#766)
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, cla: yes

#788 hotfix: Disable new behaviour for ENABLE_EXTERNAL_NAME_ALIAS
  api/v1alpha2/istio_merge.go
  api/v1alpha2/merge_test.go
  controllers/istio_controller.go
  docs/release-notes/1.7.0.md
  docs/user/04-00-istio-custom-resource.md
  internal/istiooperator/merge_experimental_test.go
  pkg/lib/annotations/annotations.go
Labels: lgtm, size/L, cla: yes

#789 [release-1.5] hotfix: Disable new behaviour for ENABLE_EXTERNAL_NAME_ALIAS
  api/v1alpha2/istio_merge.go
  api/v1alpha2/merge_test.go
  controllers/istio_controller.go
  docs/release-notes/1.5.3.md
  docs/user/04-00-istio-custom-resource.md
  internal/istiooperator/merge_experimental_test.go
  pkg/lib/annotations/annotations.go
  tests/integration/scripts/deploy-latest-release-to-cluster.sh
Labels: lgtm, size/L, cla: yes

#790 [release-1.6] hotfix: Disable new behaviour for ENABLE_EXTERNAL_NAME_ALIAS
  api/v1alpha2/istio_merge.go
  api/v1alpha2/merge_test.go
  controllers/istio_controller.go
  docs/release-notes/1.6.1.md
  docs/user/04-00-istio-custom-resource.md
  internal/istiooperator/merge_experimental_test.go
  pkg/lib/annotations/annotations.go
Labels: lgtm, size/L, cla: yes

#793 Sec scanner config and version for 1.6.1
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#792 Sec scanners and version for 1.5.3
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#794 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#796 Set up priority class for istio manager
  config/manager/manager.yaml
Labels: lgtm, size/XS, cla: yes

#804 Rate limit PoC
  docs/contributor/draft/rate-limiting-poc/01-rate-limiting.md
  docs/contributor/draft/rate-limiting-poc/02-local-rate-limiting.md
  docs/contributor/draft/rate-limiting-poc/03-global-rate-limiting.md
  docs/contributor/draft/rate-limiting-poc/global/scenario-1-limit-by-dynamic-header-values.yaml
  docs/contributor/draft/rate-limiting-poc/global/scenario-1-limit-by-static-header-values.yaml
  docs/contributor/draft/rate-limiting-poc/global/scenario-2-limit-by-header-existence.yaml
  docs/contributor/draft/rate-limiting-poc/global/scenario-3-limit-by-client-ip.yaml
  docs/contributor/draft/rate-limiting-poc/global/scenario-4-limit-by-client-cert.yaml
  docs/contributor/draft/rate-limiting-poc/global/scenario-5-limit-by-multiple-criteria.yaml
  docs/contributor/draft/rate-limiting-poc/global/scenario-6-limit-for-all-requests.yaml
  docs/contributor/draft/rate-limiting-poc/global/scenario-7-limit-on-service-sidecar.yaml
  docs/contributor/draft/rate-limiting-poc/local/scenario-1-limit-by-static-header-values.yaml
  docs/contributor/draft/rate-limiting-poc/local/scenario-2-limit-by-header-existence.yaml
  docs/contributor/draft/rate-limiting-poc/local/scenario-3-limit-by-client-ip.yaml
  docs/contributor/draft/rate-limiting-poc/local/scenario-4-limit-by-static-client-cert.yaml
  docs/contributor/draft/rate-limiting-poc/local/scenario-5-limit-by-multiple-criteria.yaml
  docs/contributor/draft/rate-limiting-poc/local/scenario-7-limit-on-gateway.yaml
  docs/contributor/draft/rate-limiting-poc/perf_tests/global-local/summary-no-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/global-local/summary-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/global/rate-limit-on-gateway/summary-no-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/global/rate-limit-on-gateway/summary-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/global/rate-limit-on-sidecar/summary-no-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/global/rate-limit-on-sidecar/summary-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/local/rate-limit-on-gateway/summary-no-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/local/rate-limit-on-gateway/summary-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/local/rate-limit-on-sidecar/summary-no-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/local/rate-limit-on-sidecar/summary-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/no-rate-limit/summary-no-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/no-rate-limit/summary-sidecar.html
  tests/performance/load-testing/templates/rate-limit.yaml
  tests/performance/load-testing/values.yaml
  tests/performance/scripts/common.js
Labels: size/XXL, cla: yes

#803 Switch to the default cni pair pods configuration to repair the pods
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
Labels: lgtm, size/XS, cla: yes

#802 Upgrade to Istio 1.21.2
  Makefile
  docs/release-notes/1.7.0.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm, cla: yes

#809 Upgrade to Istio 1.21.2 (#802)
  Makefile
  docs/release-notes/1.6.2.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#795 Deprecate kyma provision k3d command
  docs/contributor/01-00-installation.md
  tests/ui/scripts/k3d-local-dev.sh
Labels: lgtm, size/XS, cla: yes

#811 Update sec scanners and version to 1.6.2
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#815 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#813 Istio troubleshooting guide on install fail due to mod resource
  docs/user/troubleshooting/03-70-reconciliation-fails-on-istio-install.md
Labels: size/S, lgtm, cla: yes

#816 Add Request Authentication UI
  config/ui-extensions/kustomization.yaml
  config/ui-extensions/requestauthentications/dataSources
  config/ui-extensions/requestauthentications/details
  config/ui-extensions/requestauthentications/form
  config/ui-extensions/requestauthentications/general
  config/ui-extensions/requestauthentications/kustomization.yaml
  config/ui-extensions/requestauthentications/translations
  docs/release-notes/1.7.0.md
  tests/ui/cypress.config.ts
  tests/ui/fixtures/pod-httpbin-sleep.yaml
  tests/ui/support/input.ts
  tests/ui/support/k8sclient/commands.ts
  tests/ui/support/k8sclient/index.ts
  tests/ui/support/k8sclient/pod.ts
  tests/ui/support/navigation.ts
  tests/ui/support/resource/commands.ts
  tests/ui/support/resource/index.ts
  tests/ui/support/resource/requestAuthentication.ts
  tests/ui/support/resource/serviceEntry.ts
  tests/ui/support/resource/sidecar.ts
  tests/ui/tests/requestAuthentications.spec.ts
Labels: lgtm, size/L, cla: yes

#812 Hana DB connectivity troubleshooting guide
  docs/user/troubleshooting/03-70-cannot-connect-to-hana-db.md
Labels: lgtm, size/M, cla: yes

#828 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#829 Unify CRs description in Kyma dashboard
  config/ui-extensions/istios/general
Labels: documentation, lgtm, size/XS, cla: yes

#823 Skip restart of pods with proxies with istio's custom image annotation
  Makefile
  docs/release-notes/1.7.0.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/00-30-overview-istio-sidecars.md
  pkg/lib/sidecars/pods/filter.go
  pkg/lib/sidecars/pods/filter_test.go
Labels: lgtm, size/M, cla: yes

#819 Adapt HPA values and scaling base
  docs/release-notes/1.7.0.md
  docs/user/00-50-resource-configuration.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
Labels: size/S, lgtm, cla: yes

#833 Add info about upgrades and dowongrades
  docs/user/00-10-overview-istio-controller.md
Labels: lgtm, size/XS, cla: yes

#825 Deprecate kyma provision gardener
  .github/workflows/main-integration.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/pull-integration-gardener.yaml
  hack/ci/provision-gardener.sh
  hack/ci/shoot_aws.yaml
  hack/ci/shoot_gcp.yaml
Labels: lgtm, size/L, cla: yes

#835 Fix deprecate kyma provision gardener
  hack/ci/provision-gardener.sh
Labels: lgtm, size/XS, cla: yes

#843 Update sec-scanners-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#840 Use the default Gardener network addresses
  hack/ci/shoot_aws.yaml
  hack/ci/shoot_gcp.yaml
Labels: lgtm, size/XS, cla: yes

#851 Run tests on Gardener live
  .github/workflows/main-integration.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/pull-integration-gardener.yaml
  tests/integration/scripts/gardener-kubeconfig.sh
Labels: size/S, lgtm, cla: yes
