Repository kyma-project/istio, pull requests merged in 2024-03, with the labels that each got.

#653 Update security scanners config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#656 Fix gardener provisioning
  .github/workflows/main-integration.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/pull-integration-gardener.yaml
Labels: lgtm, size/XS, cla: yes

#657 Add parameter to gardener provisioning command
  hack/ci/provision-gardener.sh
Labels: lgtm, size/XS, cla: yes

#654 Add unknown condition
  api/v1alpha2/conditions.go
  api/v1alpha2/istio_types.go
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/steps/istio_cr.go
Labels: lgtm, size/L, cla: yes

#662 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#663 Add a tutorial to the sidebar
  docs/user/_sidebar.md
  docs/user/operation-guides/02-30-enable-istio-access-logs.md
  docs/user/tutorials/01-00-x-forwarded-for-header.md
  docs/user/tutorials/01-10-external-authorization-provider.md
  docs/user/tutorials/README.md
Labels: size/S, lgtm, cla: yes

#655 Proxies restart error should not block Ingress Gateway restart
  api/v1alpha2/conditions.go
  api/v1alpha2/istio_types.go
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  controllers/istio_types.go
  docs/assets/istio-controller-reconciliation-loop.svg
  docs/assets/istio-operator-overview.svg
  docs/contributor/04-10-technical-design.md
  internal/described_errors/described_errors.go
  internal/described_errors/described_errors_test.go
  internal/described_errors/suite_test.go
  internal/reconciliations/istio/configuration.go
  internal/reconciliations/istio_resources/reconciliation_test.go
  internal/reconciliations/proxy/sidecars.go
  internal/restarter/ingress_gateway.go
  internal/restarter/ingress_gateway_test.go
  internal/restarter/restart.go
  internal/restarter/restart_test.go
  internal/restarter/sidecars.go
  internal/restarter/sidecars_test.go
  internal/restarter/suite_test.go
Labels: size/XXL, lgtm, cla: yes

#666 Fix gardener provisioning (#656)
  .github/workflows/main-integration.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/pull-integration-gardener.yaml
Labels: lgtm, size/XS, cla: yes

#667 Add parameter to gardener prov command (#657)
  hack/ci/provision-gardener.sh
Labels: lgtm, size/XS, cla: yes

#668 Update VERSION and sec-scanners-config
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#672 Update dependabot.yml
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#665 Update ci-cd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#675 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#683 Update controller-tools
  .github/actions/integration-test/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-integration-test/action.yaml
  .github/workflows/main-cache.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/pull-integration-gardener.yaml
  .github/workflows/pull-request.yaml
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  tests/ui/package.json
Labels: size/XXL, lgtm, cla: yes

#682 go 1.22 update
  .github/workflows/ui-tests.yaml
  go.mod
  pkg/lib/sidecars/test/helpers/helpers.go
Labels: lgtm, size/XS, cla: yes

#686 Update managers metrics address
  config/manager/manager.yaml
  docs/release-notes/1.4.1.md
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#687 Fix links to sections in Technical Design
  docs/contributor/04-10-technical-design.md
Labels: area/documentation, lgtm, size/XS, cla: yes

#689 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#674 Istio troubleshooting guide
  docs/user/troubleshooting/03-00-istio-basic-diagnostics.md
Labels: size/S, lgtm, cla: yes

#692 Wait for istio to get Ready
  tests/integration/features/istio/production/main-suite/istio_observability.feature
Labels: lgtm, size/XS, cla: yes

#664 Revisit manifests and controlled resources list in Istio operator
  .gitignore
  Dockerfile
  api/v1alpha2/istio_merge.go
  api/v1alpha2/merge_test.go
  api/v1alpha2/resources.go
  api/v1alpha2/resources_test.go
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  docs/contributor/04-10-technical-design.md
  docs/release-notes/1.5.0.md
  docs/user/00-30-overview-istio-sidecars.md
  docs/user/operation-guides/02-30-enable-istio-access-logs.md
  docs/user/troubleshooting/03-40-incompatible-istio-sidecar-version.md
  docs/user/tutorials/01-10-external-authorization-provider.md
  internal/clusterconfig/clusterconfig.go
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  internal/istiooperator/istiooperator.go
  internal/istiooperator/istiooperator_test.go
  internal/manifest/manifest.go
  internal/manifest/manifest_test.go
  internal/manifest/test/template-operator.yaml
  internal/manifest/test/test-operator.yaml
  internal/manifest/test/wrong-operator.yaml
  internal/reconciliations/istio/configuration.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/istio/test/test_controlled_resource_list.yaml
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.go
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer_test.go
  internal/reconciliations/istio_resources/peer_authentication_mtls.go
  internal/reconciliations/istio_resources/peer_authentication_mtls_test.go
  internal/resources/controlled_resources_list.yaml
  internal/resources/disclaimer_annotation_test.go
  internal/resources/istio_resources_finder.go
  internal/resources/istio_resources_finder_test.go
  internal/resources/resources.go
  internal/resources/resources_test.go
  internal/resources/test_files/test_resources_list.yaml
  internal/resources/test_files/test_wrong_resources_list.yaml
  internal/restarter/sidecars.go
  internal/restarter/sidecars_test.go
  internal/status/status_test.go
  internal/validation/validation_test.go
  pkg/lib/gatherer/gatherer.go
  pkg/lib/gatherer/gatherer_test.go
  pkg/lib/sidecars/pods/get.go
  pkg/lib/sidecars/pods/get_test.go
  pkg/version/version.go
  tests/integration/steps/deployment.go
  tests/integration/steps/istio.go
  tests/integration/steps/resource.go
Labels: size/XXL, lgtm, cla: yes

#691 Add UI instructions to the Istio Access Logs tutorial
  docs/user/operation-guides/02-30-enable-istio-access-logs.md
Labels: lgtm, size/L, cla: yes

#696 Update istio update issue template
  .github/ISSUE_TEMPLATE/istio_update.md
Labels: lgtm, size/XS, cla: yes
