Repository kyma-project/istio, pull requests merged in 2024-11, with the labels that each got.

#1106 Check cluster info if it's not created within timeout
  hack/ci/provision-gardener.sh
Labels: size/S, lgtm, cla: yes

#1107 Fix broken issue template
  .github/ISSUE_TEMPLATE/issue.md
Labels: size/S, lgtm, cla: yes

#1108 Show namespace status when it's not removed in tests
  tests/integration/steps/resource.go
Labels: lgtm, size/XS, cla: yes

#1110 chore: consolidate job statuses in PRs into one
  .github/workflows/main-integration.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/pull-integration-gardener-release.yaml
  .github/workflows/pull-integration-gardener.yaml
  .github/workflows/pull-integration-release.yaml
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request-release.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/pull-unit-lint.yaml
  .github/workflows/ui-tests.yaml
  .github/workflows/verify-commit-pins.yaml
Labels: lgtm, area/ci, size/L, kind/chore, cla: yes

#1111 bug: always run status action
  .github/workflows/pull-request-release.yaml
  .github/workflows/pull-request.yaml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1113 Bump istio-manager main image for sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1114 feat: Enable prometheusMerge feature
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
Labels: lgtm, size/XS, cla: yes

#1116 chore: separate main and release images
  .github/workflows/create-release.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/pull-integration-gardener-release.yaml
  .github/workflows/pull-integration-release.yaml
  .github/workflows/pull-request-release.yaml
  .github/workflows/ui-tests-periodic.yaml
  .github/workflows/update-sec-scanner.yaml
  scripts/publish_assets.sh
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1118 chore: update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1121 Update release branch in Dependabot config
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1125 Update repository path of images to match new format
  .github/workflows/create-release.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/ui-tests-periodic.yaml
Labels: lgtm, size/XS, cla: yes

#1124 Bump istio main image for sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1126 Reduce upgrade test flakiness
  tests/integration/scripts/test-zero-downtime-upgrade.sh
Labels: size/S, lgtm, cla: yes

#1128 Increase timeout for provisioning Gardener cluster
  hack/ci/provision-gardener.sh
Labels: lgtm, size/XS, cla: yes

#1127 Add multizone podAntiAffinity for Istio ingressGateways
  internal/istiooperator/istio-operator.yaml
Labels: size/S, lgtm, cla: yes

#1129 Add docs about zone based podAntiAffinity rules
  docs/release-notes/1.11.0.md
  docs/user/tutorials/01-00-x-forwarded-for-header.md
Labels: lgtm, size/XS, cla: yes

#1130 bug: fix fetching main image from registy
  .github/workflows/update-sec-scanner.yaml
Labels: kind/bug, size/S, lgtm, area/ci, cla: yes

#1131 Add manager and istio logs in tests
  .github/actions/integration-test/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
Labels: lgtm, size/M, cla: yes

#1134 bug: add refs fetch in update-sec-scanner.yaml
  .github/workflows/update-sec-scanner.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#1135 bug: add refs fetch in update-sec-scanner.yaml
  .github/workflows/update-sec-scanner.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#1139 chore: remove custom labels from dependabot.yml
  .github/dependabot.yml
Labels: size/S, lgtm, area/ci, kind/chore, cla: yes

#1143 chore: change token in update-sec-scanner.yaml
  .github/workflows/update-sec-scanner.yaml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1147 Add Istio 1.24.1 to images
  external-images.yaml
Labels: lgtm, size/XS, cla: yes

#1148 chore: change git user to kyma-goat-bot
  .github/workflows/update-sec-scanner.yaml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1150 chore: add explicit usage of custom GITHUB_TOKEN
  .github/workflows/update-sec-scanner.yaml
Labels: size/S, lgtm, area/ci, kind/chore, cla: yes

#1151 chore: change default token in checkout action
  .github/workflows/update-sec-scanner.yaml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1145 feat: workflow to add dependabot PRs to project
  .github/workflows/pr-add-dependabot-to-project.yaml
Labels: kind/feature, area/ci, size/L, cla: yes

#1156 bug: change schedule of update-sec-scanner.yaml
  .github/workflows/update-sec-scanner.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#1157 Remove Rate Limit ADR
  docs/assets/istio-operator-overview-ratelimit.svg
  docs/contributor/adr/0008-rate-limit.md
Labels: lgtm, size/L, cla: yes
