Repository kyma-project/istio, pull requests merged in 2024-04, with the labels that each got.

#699 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#695 Load testing update
  .github/workflows/performance-test.yaml
  hack/ci/gardener-perf-test.sh
  tests/performance/.gitignore
  tests/performance/Makefile
  tests/performance/hack/puppeteer/export.js
  tests/performance/hack/puppeteer/export.sh
  tests/performance/hack/puppeteer/package-lock.json
  tests/performance/hack/puppeteer/package.json
  tests/performance/load-testing/.gitignore
  tests/performance/load-testing/Chart.lock
  tests/performance/load-testing/Chart.yaml
  tests/performance/load-testing/templates/dns-entry.yaml
  tests/performance/load-testing/templates/grafana-dashboard.yaml
  tests/performance/load-testing/templates/grafana-providers.yaml
  tests/performance/load-testing/templates/httpbin.yaml
  tests/performance/load-testing/templates/kyma-gateway.yaml
  tests/performance/load-testing/templates/vs-grafana.yaml
  tests/performance/load-testing/values.yaml
  tests/performance/scripts/common.js
Labels: size/XXL, lgtm, cla: yes

#701 Update performance-test.yaml
  .github/workflows/performance-test.yaml
Labels: lgtm, size/XS, cla: yes

#676 Update istio to 1.21.0
  controllers/istio_controller.go
  controllers/suite_test.go
  docs/release-notes/1.5.0.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/istio/metadata.go
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.go
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.yaml
  internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer_test.go
  internal/reconciliations/istio_resources/reconciliation.go
  internal/reconciliations/istio_resources/reconciliation_test.go
  internal/resources/controlled_resources_list.yaml
  internal/resources/disclaimer_annotation_test.go
  internal/restarter/ingress_gateway.go
  internal/restarter/ingress_gateway_test.go
  sec-scanners-config.yaml
  tests/integration/features/istio/evaluation/istio_installation_demo.feature
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/features/istio/production/main-suite/istio_resources.feature
  tests/integration/main_test.go
  tests/integration/steps/destination_rule.go
  tests/integration/steps/istio.go
  tests/integration/steps/istio_crd_list.yaml
  tests/integration/steps/resource.go
Labels: size/XXL, lgtm, cla: yes

#700 bug: Node-based provider discovery
  controllers/istio_controller.go
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/clusterconfig/hyperscaler.go
  internal/clusterconfig/hyperscaler_test.go
  internal/reconciliations/istio_resources/reconciliation.go
  internal/reconciliations/istio_resources/reconciliation_test.go
Labels: kind/bug, area/service-mesh, lgtm, size/L, cla: yes

#705 Cherrypick "bug: Node-based provider discovery (#700)"
  controllers/istio_controller.go
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/clusterconfig/hyperscaler.go
  internal/clusterconfig/hyperscaler_test.go
  internal/reconciliations/istio_resources/reconciliation.go
  internal/reconciliations/istio_resources/reconciliation_test.go
Labels: kind/bug, area/service-mesh, lgtm, size/L, cla: yes

#704 Update VERSION file and sec scanner config for release
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#708 bug: Node-based provider discovery (#700)
  controllers/istio_controller.go
  docs/release-notes/1.4.2.md
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/clusterconfig/hyperscaler.go
  internal/clusterconfig/hyperscaler_test.go
  internal/reconciliations/istio_resources/reconciliation.go
  internal/reconciliations/istio_resources/reconciliation_test.go
Labels: kind/bug, area/service-mesh, lgtm, size/L, cla: yes

#709 Update sec scanners and version to 1.4.2
  VERSION
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#710 Update dependabot to release 1.5
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#712 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#713 Add tutorial to sidebar
  docs/user/_sidebar.md
  docs/user/troubleshooting/README.md
Labels: size/S, lgtm, cla: yes

#715 Correct a link in the sidebar
  docs/user/_sidebar.md
Labels: lgtm, size/XS, cla: yes

#716 Update Istio to 1.21.1
  docs/release-notes/1.6.0.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#719 Update Istio to 1.21.1
  docs/release-notes/1.5.1.md
  docs/release-notes/1.6.0.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/L, cla: yes

#714 feat: Enable experimental features handling from CR code
  api/v1alpha2/experimental.go
  api/v1alpha2/istio_types.go
  controllers/istio_controller.go
  controllers/validate.go
  controllers/validate_experimental.go
  controllers/validate_test.go
  docs/release-notes/1.6.0.md
  docs/user/04-00-istio-custom-resource.md
  internal/istiooperator/istiooperator.go
  internal/istiooperator/merge.go
  internal/istiooperator/merge_experimental.go
  internal/istiooperator/merge_experimental_test.go
Labels: kind/feature, area/service-mesh, lgtm, size/L, cla: yes

#726 feat: Enable experimental features handling from CR code
  api/v1alpha2/experimental.go
  api/v1alpha2/istio_types.go
  controllers/istio_controller.go
  controllers/validate.go
  controllers/validate_experimental.go
  controllers/validate_test.go
  docs/release-notes/1.5.2.md
  docs/release-notes/1.6.0.md
  docs/user/04-00-istio-custom-resource.md
  internal/istiooperator/istiooperator.go
  internal/istiooperator/merge.go
  internal/istiooperator/merge_experimental.go
  internal/istiooperator/merge_experimental_test.go
Labels: kind/feature, area/service-mesh, lgtm, size/L, cla: yes

#729 fix: update API and autogen code
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
Labels: lgtm, size/L, cla: yes

#730 fix: update API and autogen code (#729)
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
Labels: lgtm, size/L, cla: yes

#734 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#731 Extend workflows to support experimental manager
  .github/workflows/create-release.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/ui-tests.yaml
  Dockerfile
  Makefile
  README.md
  docs/contributor/01-00-installation.md
  docs/contributor/04-30-ci-cd.md
  docs/release-notes/template.md
  scripts/publish_assets.sh
Labels: lgtm, size/L, cla: yes

#738 chore: add gitleaks to repo
  .github/workflows/pull-gitleaks.yaml
  .gitleaks.toml
Labels: size/XXL, lgtm, area/ci, kind/chore, cla: yes

#739 Ignore dot files workflows that run tests
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-gardener.yaml
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request.yaml
Labels: lgtm, size/XS, cla: yes

#740 Add permalinks for newly added CI/CD jobs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/XS, cla: yes

#741 docs: add gitleaks docu
  docs/contributor/04-30-ci-cd.md
Labels: size/S, lgtm, area/ci, kind/chore, cla: yes

#747 Fix manager release artifact
  scripts/publish_assets.sh
Labels: lgtm, size/XS, cla: yes

#748 Fix manager release artifact on main
  scripts/publish_assets.sh
Labels: lgtm, size/XS, cla: yes

#752 Fix version replacement for assets
  .gitignore
  Makefile
  config/default/kustomization.template.yaml
  scripts/publish_assets.sh
Labels: size/S, lgtm, cla: yes

#753 Cherry-pick: Fix version replacement for assets (#752)
  .gitignore
  Makefile
  config/default/kustomization.template.yaml
  scripts/publish_assets.sh
Labels: size/S, lgtm, cla: yes

#756 Add a directory with ADRs
  .github/ISSUE_TEMPLATE/adr.md
  docs/contributor/adr/0000-istio-operator-design.md
  docs/contributor/adr/0001-istio-resources-reconciliation.md
  docs/contributor/adr/0002-istio-cr-status-improvements.md
  docs/contributor/adr/0003-support-for-external-authorization-providers.md
  docs/contributor/adr/0004-configurable-log-formats-in-default-access-logs-providers.md
  docs/contributor/adr/0005-suppoert-for-experimental-configuration-parameters-in-istio-cr.md
  docs/contributor/adr/0006-support-for-externalTrafficPolicy-configuration.md
  docs/contributor/adr/adr-template.md
Labels: size/XL, lgtm, cla: yes

#759 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#758 Telemetry UI
  config/ui-extensions/kustomization.yaml
  config/ui-extensions/telemetries/details
  config/ui-extensions/telemetries/form
  config/ui-extensions/telemetries/general
  config/ui-extensions/telemetries/kustomization.yaml
  tests/ui/support/navigation.ts
  tests/ui/support/resource/commands.ts
  tests/ui/support/resource/gateway.ts
  tests/ui/support/resource/index.ts
  tests/ui/support/resource/telemetries.ts
  tests/ui/tests/telemetries.spec.ts
Labels: lgtm, size/L, cla: yes

#761 Fix links in the adr folder
  docs/contributor/adr/0000-istio-operator-design.md
  docs/contributor/adr/0002-istio-cr-status-improvements.md
Labels: lgtm, size/XS, cla: yes

#728 External traffic policy
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-gardener.yaml
  Makefile
  api/v1alpha2/istio_merge.go
  api/v1alpha2/istio_structs.go
  api/v1alpha2/merge_test.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  config/ui-extensions/istios/details
  config/ui-extensions/istios/form
  config/ui-extensions/istios/translations
  docs/release-notes/1.6.0.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/04-00-istio-custom-resource.md
  docs/user/tutorials/01-00-x-forwarded-for-header.md
  docs/user/tutorials/assets/01-00-num-trusted-proxies-ui.svg
  hack/ci/gardener-integration-gcp-specific.sh
  tests/integration/features/istio/production/aws-suite/xff_header.feature
  tests/integration/features/istio/production/gcp-suite/xff_header.feature
  tests/integration/main_test.go
  tests/integration/scripts/integration-test-aws-specific.sh
  tests/integration/scripts/integration-test-gardener.sh
  tests/integration/scripts/jobguard.sh
  tests/integration/scripts/provison-gardener.sh
  tests/integration/steps/istio_cr_template.yaml
Labels: size/XL, lgtm, cla: yes

#764 Make new script executable
  hack/ci/gardener-integration-gcp-specific.sh
Labels: lgtm, size/XS, cla: yes

#766 workflows: add experimental tagging
  .github/workflows/create-release.yaml
Labels: lgtm, size/XS, cla: yes

#765 Warning about externalTrafficPolicy switch
  api/v1alpha2/istio_structs.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  docs/release-notes/1.6.0.md
  docs/user/tutorials/01-00-x-forwarded-for-header.md
Labels: size/S, lgtm, cla: yes

#760 Enable istio metric rotation
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  internal/istiooperator/merge_experimental_test.go
Labels: size/S, lgtm, cla: yes

#769 dependabot config update
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#776 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#775 Remove no longer existing jobs from cicd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/XS, cla: yes

#783 Update Kyma dashboard instructions
  docs/user/operation-guides/02-30-enable-istio-access-logs.md
Labels: lgtm, size/M, cla: yes
