Repository kyma-project/istio, pull requests merged in 2024-01, with the labels that each got.

#544 chore: bump istio to 1.20.1
  VERSION
  controllers/istio_controller.go
  docs/release-notes/1.2.1.md
  go.mod
  go.sum
  sec-scanners-config.yaml
Labels: area/service-mesh, lgtm, size/M, kind/chore, cla: yes

#545 Add missing files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  NOTICE.md
  README.md
  SECURITY.md
Labels: size/S, lgtm, cla: yes

#546 Remove module template and LM testing leftovers (#524)
  .env
  .github/workflows/create-release.yaml
  Makefile
  hack/ci/Makefile
  hack/local/Makefile
  hack/local/busola/Makefile
  hack/local/busola/k3d-patches/busola-extensibility.yaml
  hack/local/busola/k3d-patches/busola-kyma-extension.yaml
  hack/local/istio/Makefile
  hack/local/istio/k3d-patches/patch-k3d-lifecycle-manager-clusterrole.yaml
Labels: area/service-mesh, lgtm, tide/merge-method-merge, size/L, kind/chore, cla: yes

#547 chore: bump istio to 1.20.1 (#544)
  VERSION
  controllers/istio_controller.go
  docs/release-notes/1.2.1.md
  go.mod
  go.sum
  sec-scanners-config.yaml
Labels: area/service-mesh, lgtm, size/M, tide/merge-method-merge, kind/chore, cla: yes

#520 Istio Status Conditions
  Makefile
  api/v1alpha1/istio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  controllers/istio_types.go
  controllers/status.go
  controllers/status_test.go
  docs/release-notes/1.3.0.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/04-00-istio-custom-resource.md
  docs/user/troubleshooting/03-10-503-no-access.md
  internal/described_errors/described_errors.go
  internal/reconciliations/istio/configuration.go
  internal/reconciliations/istio/configuration_test.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/installation_test.go
  internal/reconciliations/istio_resources/reconciliation.go
  internal/reconciliations/proxy/sidecars.go
  internal/reconciliations/proxy/sidecars_test.go
  internal/status/status.go
  internal/status/status_test.go
  pkg/lib/sidecars/proxy.go
  pkg/lib/sidecars/restart/warning_action.go
  pkg/lib/sidecars/test/cases.go
  tests/integration/features/istio/evaluation/istio_installation_demo.feature
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/scenario.go
  tests/integration/steps/istio_cr.go
Labels: size/XXL, lgtm, cla: yes

#554 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#555 Make k6 logs quiet
  tests/performance/Makefile
Labels: lgtm, size/XS, cla: yes

#559 Add sleep to Istio performance test
  tests/performance/Makefile
Labels: lgtm, size/XS, cla: yes

#558 Add Istio operator metrics service
  config/manager/kustomization.yaml
  config/manager/metrics_service.yaml
  main.go
Labels: size/S, lgtm, cla: yes

#562 Fix UI test
  tests/ui/support/navigation.js
Labels: lgtm, size/XS, cla: yes

#566 Security scanner config update
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#508 feat: Switch to opentelemetry tracer and harmonize service naming
  docs/release-notes/1.3.0.md
  manifests/istio-operator-template-light.yaml
  manifests/istio-operator-template.yaml
Labels: size/S, lgtm, cla: yes

#561 Revisit Issue and PR templates
  .github/ISSUE_TEMPLATE/adr.md
  .github/ISSUE_TEMPLATE/deprecation_deletion.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull-request-template.md
Labels: lgtm, size/M, cla: yes

#575 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#583 Update links
  docs/user/_sidebar.md
  docs/user/operation-guides/02-30-enable-istio-access-logs.md
Labels: size/S, lgtm, cla: yes

#586 Update links
  docs/contributor/01-00-installation.md
  docs/user/00-30-overview-istio-sidecars.md
Labels: lgtm, size/XS, cla: yes

#589 Fix md links
  README.md
  hack/managed-kyma-migration/readme.md
Labels: lgtm, size/XS, cla: yes

#576 Observability integration tests
  tests/integration/features/istio/production/main-suite/istio_observability.feature
  tests/integration/main_test.go
  tests/integration/scenario.go
  tests/integration/steps/deployment.go
  tests/integration/steps/logs.go
  tests/integration/steps/observability.go
Labels: lgtm, size/L, cla: yes

#590 Istio Release 1.3
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#591 Fix dependabot config for release-1.3
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#587 Make sure security scanner configuration is updated before release
  .github/workflows/create-release.yaml
  main.go
Labels: size/S, lgtm, cla: yes
