Repository kyma-project/istio, pull requests merged in 2024-08, with the labels that each got.

#960 bug: use proper secret in a workflow
  .github/workflows/update-sec-scanner.yaml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#931 tutorials for exposing workloads with gateway API
  docs/user/_sidebar.md
  docs/user/tutorials/01-20-expose-httbin-gateway-api.md
  docs/user/tutorials/01-30-expose-tcp-gateway-api.md
Labels: lgtm, size/L, cla: yes

#962 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#951 Rate limit ADR update
  docs/contributor/adr/0008-rate-limit.md
Labels: lgtm, size/L, cla: yes

#967 feat: update provision-gardener.sh with retry logic
  hack/ci/provision-gardener.sh
Labels: kind/feature, lgtm, size/M, area/ci, cla: yes

#973 Fix Docker warning
  Dockerfile
Labels: lgtm, size/XS, cla: yes

#974 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#977 Fix the rendering of code blocks
  docs/user/tutorials/01-20-expose-httbin-gateway-api.md
  docs/user/tutorials/01-30-expose-tcp-gateway-api.md
Labels: size/S, lgtm, cla: yes

#976 Unserve v1alpha1 in CRD
  api/v1alpha1/istio_types.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
Labels: lgtm, size/XS, cla: yes

#975 Migration guide for Service ExternalName Istio changed behavior
  docs/user/migration/external-name-alias.md
Labels: lgtm, size/L, cla: yes

#980 Unserve v1alpha1 in CRD
  Makefile
  api/v1alpha1/istio_types.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  pkg/lib/sidecars/test/restart_test.go
Labels: size/S, lgtm, cla: yes

#978 cicd: bump k8s version in the int tests
  .github/actions/integration-test/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/provision-k3d-cluster/action.yaml
  .github/actions/upgrade-integration-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-gardener.yaml
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request.yaml
  pkg/lib/sidecars/test/restart_test.go
Labels: lgtm, size/L, cla: yes

#981 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#983 Fix formatting in the Gateway API tutorial
  docs/user/tutorials/01-20-expose-httbin-gateway-api.md
  docs/user/tutorials/01-30-expose-tcp-gateway-api.md
Labels: size/S, lgtm, cla: yes

#985 Fix gardener provision bash scripts
  hack/ci/provision-gardener.sh
Labels: size/S, lgtm, cla: yes

#984 Change certificate key size to 4096 bits
  docs/release-notes/1.8.3.md
  docs/user/00-40-overview-istio-setup.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  internal/istiooperator/istiooperator.go
Labels: size/S, lgtm, cla: yes

#987 Change certificate key size to 4096 bits (#984)
  docs/release-notes/1.8.3.md
  docs/user/00-40-overview-istio-setup.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  internal/istiooperator/istiooperator.go
Labels: size/S, lgtm, cla: yes

#988 Release 1.8.3
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#990 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes
