Repository kyma-project/istio, pull requests merged in 2024-06, with the labels that each got.

#853 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#847 Istio Version documentation
  .github/ISSUE_TEMPLATE/istio_update.md
  README.md
  docs/release-notes/template.md
  docs/user/README.md
  scripts/create_draft_release.sh
  scripts/get_module_envoy_version.sh
  scripts/get_module_istio_version.sh
Labels: lgtm, size/M, cla: yes

#850 Use one workflow and switch path ignore to filter action
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-gardener.yaml
  .github/workflows/pull-integration.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/pull-unit-lint.yaml
  .github/workflows/ui-tests.yaml
  .github/workflows/verify-commit-pins.yaml
Labels: lgtm, size/L, cla: yes

#860 Improve memory usage of Istio manager (#852)
  .github/workflows/main-integration.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/pull-integration-gardener.yaml
  .github/workflows/verify-commit-pins.yaml
  hack/ci/provision-gardener.sh
  hack/ci/shoot_aws.yaml
  hack/ci/shoot_gcp.yaml
  main.go
  pkg/lib/sidecars/pods/get.go
  pkg/lib/sidecars/remove/remove.go
  pkg/lib/sidecars/restart/restart.go
  pkg/lib/sidecars/restart/restart_test.go
  tests/integration/scripts/gardener-kubeconfig.sh
Labels: lgtm, size/L, cla: yes

#863 Update sec-scanners-config.yaml and version file for 1.6.3
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#864 Create 1.6.3.md
  docs/release-notes/1.6.3.md
Labels: lgtm, size/XS, cla: yes

#865 CI/CD documentation for enforcing rules
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#869 Fix Busola UI
  config/ui-extensions/telemetries/general
  docs/release-notes/1.6.3.md
  main.go
  tests/ui/support/navigation.ts
  tests/ui/tests/virtualServices.spec.ts
Labels: size/S, lgtm, cla: yes

#868 Skip VirtualService tests
  tests/ui/tests/virtualServices.spec.ts
Labels: lgtm, size/XS, cla: yes

#856 fix: Use a custom path for telemetries UI to avoid conflicts with kyma telemetry resources
  config/ui-extensions/telemetries/general
  tests/ui/support/navigation.ts
Labels: lgtm, size/XS, cla: yes

#866 Automate rollout of Istio module
  .github/workflows/rollout-module.yaml
Labels: area/service-mesh, lgtm, size/L, cla: yes

#872 Fix typo in rollout module
  .github/workflows/rollout-module.yaml
Labels: lgtm, size/XS, cla: yes

#855 Set Istio CR to warning on version update that is not allowed
  README.md
  api/v1alpha2/conditions.go
  api/v1alpha2/istio_types.go
  docs/release-notes/1.7.0.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/README.md
  internal/reconciliations/istio/configuration.go
  internal/reconciliations/istio/finalizer.go
  internal/reconciliations/istio/install.go
  internal/reconciliations/istio/installation.go
  internal/reconciliations/istio/reconciliation.go
  internal/reconciliations/istio/reconciliation_test.go
  internal/reconciliations/istio/uninstall.go
Labels: size/XL, lgtm, cla: yes

#875 Disable test controller restart verification hook
  tests/integration/hooks.go
Labels: lgtm, size/M, cla: yes

#849 feat: compatibility mode
  .github/ISSUE_TEMPLATE/istio_update.md
  .github/workflows/main-integration.yaml
  Makefile
  api/v1alpha2/compatibility_mode.go
  api/v1alpha2/compatibility_mode_test.go
  api/v1alpha2/istio_merge.go
  api/v1alpha2/istio_types.go
  api/v1alpha2/merge_test.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  config/ui-extensions/istios/details
  config/ui-extensions/istios/form
  config/ui-extensions/istios/translations
  docs/contributor/adr/0006-support-for-externalTrafficPolicy-configuration.md
  docs/contributor/adr/0007-compatibilityMode.md
  docs/release-notes/1.7.0.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/04-00-istio-custom-resource.md
Labels: lgtm, size/L, cla: yes

#880 Remove hook that verifies if controller was restarted in integration tests
  tests/integration/hooks.go
  tests/integration/scenario.go
Labels: lgtm, size/M, cla: yes

#877 Bump Istio to 1.21.3
  README.md
  docs/release-notes/1.7.0.md
  docs/user/README.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  internal/reconciliations/istio/client.go
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#885 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#882 Bump Istio to 1.21.3
  README.md
  docs/release-notes/1.6.4.md
  docs/user/README.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#886 Release 1.6.4
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#881 Remove one of the compatibility envs and move docs
  README.md
  api/v1alpha2/compatibility_mode.go
  docs/user/00-10-overview-istio-controller.md
  docs/user/04-00-istio-custom-resource.md
  docs/user/README.md
Labels: size/S, lgtm, cla: yes

#888 Fix readme formatting
  README.md
  docs/user/README.md
Labels: lgtm, size/XS, cla: yes

#889 Update VERSION and sec scanner
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#890 Update rollout-module.yaml
  .github/workflows/rollout-module.yaml
Labels: lgtm, size/XS, cla: yes

#879 Exclude k8s.io dependencies from Dependabot bumps
  .github/ISSUE_TEMPLATE/istio_update.md
  .github/dependabot.yml
Labels: size/S, lgtm, cla: yes

#891 Update security scanner image
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#892 Update troubleshooting sidebar and README
  docs/user/_sidebar.md
  docs/user/troubleshooting/03-70-reconciliation-fails-on-istio-install.md
  docs/user/troubleshooting/03-80-cannot-connect-to-hana-db.md
  docs/user/troubleshooting/README.md
Labels: size/S, lgtm, cla: yes

#893 Use title case
  docs/user/troubleshooting/03-70-reconciliation-fails-on-istio-install.md
Labels: lgtm, size/XS, cla: yes

#887 Istio 1.22.1
  README.md
  api/v1alpha2/compatibility_mode.go
  api/v1alpha2/compatibility_mode_test.go
  api/v1alpha2/istio_merge.go
  cmd/istio-install/main.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  controllers/istio_controller.go
  controllers/suite_test.go
  docs/release-notes/1.8.0.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/README.md
  docs/user/tutorials/01-10-external-authorization-provider.md
  go.mod
  go.sum
  internal/compatibility/proxy_restart.go
  internal/compatibility/proxy_restart_test.go
  internal/compatibility/suite_test.go
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  internal/reconciliations/istio/client.go
  internal/reconciliations/istio/configuration.go
  internal/reconciliations/istio/configuration_test.go
  internal/reconciliations/istio/install.go
  internal/reconciliations/istio/reconciliation.go
  internal/reconciliations/istio/reconciliation_test.go
  internal/reconciliations/istio/uninstall.go
  internal/reconciliations/istio_resources/peer_authentication_mtls.yaml
  internal/reconciliations/istio_resources/peer_authentication_mtls_test.go
  internal/reconciliations/istio_resources/reconciliation_test.go
  internal/resources/controlled_resources_list.yaml
  internal/resources/disclaimer_annotation_test.go
  internal/resources/resources_test.go
  internal/resources/test_files/resource_with_spec.yaml
  internal/restarter/sidecars.go
  internal/restarter/sidecars_test.go
  internal/status/status_test.go
  internal/webhooks/webhooks_test.go
  main.go
  pkg/lib/ingressgateway/ingressgateway.go
  pkg/lib/sidecars/pods/filter.go
  pkg/lib/sidecars/pods/get.go
  pkg/lib/sidecars/pods/get_test.go
  pkg/lib/sidecars/test/pod_states.go
  sec-scanners-config.yaml
  tests/integration/main_test.go
  tests/integration/steps/destination_rule.go
  tests/integration/steps/istio.go
  tests/integration/steps/observability.go
  tests/integration/steps/resource.go
  tests/performance/load-testing/templates/kyma-gateway.yaml
  tests/performance/load-testing/templates/vs-allow.yaml
  tests/performance/load-testing/templates/vs-grafana.yaml
  tests/ui/fixtures/authorizationPolicy.yaml
Labels: size/XXL, lgtm, cla: yes

#876 Add envoy Memcached rate limiting
  docs/contributor/draft/rate-limiting-poc/04-global-rate-limiting-memcached.md
  docs/contributor/draft/rate-limiting-poc/05-global-rate-limiting-valkey.md
  docs/contributor/draft/rate-limiting-poc/06-sum-up-rate-limiting.md
  docs/contributor/draft/rate-limiting-poc/perf_tests/global/memcached-gateway/summary-no-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/global/memcached-gateway/summary-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/global/memcached-sidecar/summary-no-sidecar.html
  docs/contributor/draft/rate-limiting-poc/perf_tests/global/memcached-sidecar/summary-sidecar.html
  tests/performance/load-testing/templates/rate-limit-memcached.yaml
  tests/performance/load-testing/values.yaml
Labels: size/XXL, lgtm, cla: yes

#897 Fix experimental rollout
  .github/workflows/rollout-module.yaml
Labels: lgtm, size/XS, cla: yes

#899 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#900 Update security scanners config and VERSION file
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#904 Update release branch in Dependabot config
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#905 Change the Pull Request label to a selection in the module rollout workflow
  .github/workflows/rollout-module.yaml
Labels: lgtm, size/XS, cla: yes
