Repository kyma-project/istio, pull requests merged in 2024-09, with the labels that each got.

#1001 Update security scanners config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1010 cicd: build manager with image builder on main
  .github/workflows/main-integration.yaml
  .github/workflows/verify-commit-pins.yaml
Labels: lgtm, size/M, cla: yes

#1011 cicd: Dockerfile adjustment
  Dockerfile
Labels: lgtm, size/XS, cla: yes

#1013 docs: Fix access logs for entire mesh instructions
  docs/user/operation-guides/02-30-enable-istio-access-logs.md
Labels: kind/bug, area/documentation, lgtm, size/XS, cla: yes

#1014 Add ExternalName migration blog post to the sidebar
  docs/user/_sidebar.md
  docs/user/migration/external-name-alias.md
Labels: lgtm, size/M, cla: yes

#1012 add workflow for release build with image-builder
  .github/workflows/create-release.yaml
Labels: lgtm, size/M, cla: yes

#1015 Update security scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1018 bug: move image build from steps to jobs
  .github/workflows/create-release.yaml
Labels: lgtm, size/M, cla: yes

#1029 change job for environment key in workflow
  .github/workflows/pull-request-release.yaml
Labels: lgtm, size/XS, cla: yes

#1031 Remove redundant job and fix typo
  .github/workflows/pull-integration-gardener-release.yaml
  .github/workflows/pull-request-release.yaml
Labels: size/S, lgtm, cla: yes

#1024 Bump Istio to 1.23.2
  Dockerfile
  README.md
  api/v1alpha2/compatibility_mode.go
  api/v1alpha2/compatibility_mode_test.go
  docs/release-notes/1.9.0.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/README.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/L, cla: yes

#1035 Workflow improvements
  .github/workflows/pull-request-release.yaml
Labels: lgtm, size/XS, cla: yes

#1039 Fix parameter passed to action by release int workflow
  .github/workflows/pull-integration-release.yaml
Labels: lgtm, size/XS, cla: yes

#1038 Fix ref in workflow
  .github/workflows/pull-integration-release.yaml
Labels: lgtm, size/XS, cla: yes

#1042 Fix ref in workflow (#1038)
  .github/workflows/pull-integration-release.yaml
Labels: lgtm, size/XS, cla: yes

#1033 Update cicd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#1044 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes
