Repository kyma-project/istio, pull requests merged in 2024-12, with the labels that each got.

#1149 Bump Istio to 1.24
  README.md
  api/v1alpha2/compatibility_mode.go
  api/v1alpha2/compatibility_mode_test.go
  docs/release-notes/1.12.0.md
  docs/user/README.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
  tests/integration/features/observability-suite/observability.feature
  tests/integration/steps/logs.go
  tests/integration/steps/observability.go
Labels: size/L, cla: yes

#1158 feat: add kyma-goat-bot user to autoadd PRs to board
  .github/workflows/pull-add-bot-prs-to-project.yaml
Labels: kind/feature, lgtm, size/XS, area/ci, cla: yes

#1160 Update 01-30-expose-tcp-gateway-api.md
  docs/user/tutorials/01-30-expose-tcp-gateway-api.md
Labels: lgtm, size/XS, cla: yes

#1166 bug: upload image from image-builder
  .github/workflows/pull-request-release.yaml
Labels: kind/bug, size/S, lgtm, area/ci, cla: yes

#1167 bug: upload image from image-builder (#1166)
  .github/workflows/pull-request-release.yaml
Labels: kind/bug, size/S, lgtm, area/ci, cla: yes

#1164 Update VERSION
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1169 Update release branch in Dependabot
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1179 Rename Release workflows
  .github/workflows/call-release-pr-integration-gardener.yaml
  .github/workflows/call-release-pr-integration.yaml
  .github/workflows/call-ui-tests.yaml
  .github/workflows/call-verify-commit-pins.yaml
  .github/workflows/pull-add-bot-prs-to-project.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/release-create-release.yaml
  .github/workflows/release-pr.yaml
  .github/workflows/release-rollout-module.yaml
  .github/workflows/schedule-performance-test.yaml
  .github/workflows/schedule-ui-tests-periodic.yaml
  .github/workflows/update-sec-scanner.yaml
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/L, cla: yes

#1182 fix broken links
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/XS, cla: yes

#1183 Move release notes 1.12 -> 1.11
  docs/release-notes/1.11.0.md
  docs/release-notes/1.12.0.md
Labels: lgtm, size/M, cla: yes

#1184 fix: Revert enabling prometheusMerge feature
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
Labels: lgtm, size/XS, cla: yes

#1188 bugfix: Disable prometheus merge
  docs/release-notes/1.11.1.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
Labels: lgtm, size/XS, cla: yes

#1189 Fix broken links
  docs/contributor/04-30-ci-cd.md
  docs/release-notes/1.11.0.md
Labels: lgtm, size/XS, cla: yes

#1191 Updating version to 1.11.1
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#1193 Optimise manager building time by stripping symbols
  Dockerfile
Labels: lgtm, size/XS, cla: yes

#1178 Extend Istio CR with Egress Gateway
  api/v1alpha2/conditions.go
  api/v1alpha2/istio_merge.go
  api/v1alpha2/istio_structs.go
  api/v1alpha2/istio_types.go
  api/v1alpha2/merge_test.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  docs/release-notes/1.12.0.md
  docs/user/04-00-istio-custom-resource.md
  internal/restarter/ingress_gateway.go
  pkg/lib/sidecars/pods/get.go
  tests/integration/features/configuration-suite/configuration.feature
  tests/integration/features/installation-suite/install.feature
  tests/integration/scenario.go
  tests/integration/steps/istio.go
  tests/integration/steps/istio_cr_template.yaml
Labels: lgtm, size/L, cla: yes

#1176 Testing strategy for Istio module
  docs/contributor/02-10-testing-strategy.md
Labels: lgtm, size/M, cla: yes

#1192 Switch IOP to new structure
  Makefile
  api/v1alpha2/compatibility_mode.go
  api/v1alpha2/compatibility_mode_test.go
  api/v1alpha2/istio_merge.go
  api/v1alpha2/istio_structs.go
  api/v1alpha2/merge_test.go
  api/v1alpha2/resources.go
  api/v1alpha2/resources_test.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  config/rbac/role.yaml
  controllers/istio_controller.go
  go.mod
  go.sum
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  internal/istiooperator/istiooperator.go
  internal/istiooperator/istiooperator_test.go
  internal/istiooperator/merge_experimental.go
  internal/istiooperator/merge_experimental_test.go
  internal/reconciliations/istio/client.go
  internal/reconciliations/istio/reconciliation_test.go
  internal/restarter/sidecars.go
  internal/restarter/sidecars_test.go
  internal/webhooks/webhooks_test.go
  tests/integration/main_test.go
  tests/integration/steps/resource.go
Labels: size/XXL, lgtm, cla: yes

#1196 Add egress-gateway affinity
  internal/istiooperator/istio-operator.yaml
Labels: size/S, lgtm, cla: yes

#1197 Fix egress resources
  docs/user/00-15-overview-istio-setup.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
Labels: size/S, lgtm, cla: yes

#1198 Set the same resources for egress and ingress
  docs/user/00-15-overview-istio-setup.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
Labels: size/S, lgtm, cla: yes

#1202 Bump slack action in the failed workflow notification
  .github/actions/slack-notification-failed-workflow/action.yaml
  .github/workflows/main-integration.yaml
Labels: lgtm, size/XS, cla: yes

#1205 Add owner to the slack failed tests notification
  .github/actions/slack-notification-failed-workflow/action.yaml
Labels: lgtm, size/XS, cla: yes

#1203 Bump k8s int tests
  .github/actions/integration-test/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/workflows/call-integration-tests.yaml
  .github/workflows/call-release-pr-integration-gardener.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/pull-integration-gardener.yaml
Labels: size/M, cla: yes

#1206 Update call-ui-tests.yaml
  .github/workflows/call-ui-tests.yaml
Labels: lgtm, size/XS, cla: yes

#1204 Adapt HPA and resources of egress gateway
  docs/user/00-15-overview-istio-setup.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
Labels: lgtm, size/M, cla: yes

#1207 Update VERSION and sec-scanners-config
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1187 Move release notes 1.12 -> 1.11 (#1183)
  docs/release-notes/1.11.0.md
  docs/release-notes/1.12.0.md
Labels: lgtm, size/M, cla: yes

#1105 Remove the migration guide for the external name annotation
  docs/user/_sidebar.md
  docs/user/migration/external-name-alias.md
Labels: size/L, cla: yes

#1208 Update dependabot.yml
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1220 Increase default test timeout
  tests/testcontext/config.go
Labels: lgtm, size/XS, cla: yes

#1221 UI tests workflow fix for checkout without fetch-depth
  .github/workflows/call-ui-tests.yaml
Labels: lgtm, size/XS, cla: yes

#1222 Istio 1.13.0 Release
  .github/workflows/call-ui-tests.yaml
  VERSION
  go.mod
  go.sum
  sec-scanners-config.yaml
  tests/testcontext/config.go
  tests/ui/package-lock.json
  tests/ui/package.json
Labels: lgtm, size/L, cla: yes

#1199 Create 1.13.0 release notes
  docs/release-notes/1.13.0.md
Labels: lgtm, size/XS, cla: yes

#1215 Bump dependabot for Release 1.13
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1224 Add steps to the XFF tutorial
  docs/user/_sidebar.md
  docs/user/tutorials/01-00-x-forwarded-for-header.md
Labels: lgtm, size/M, cla: yes
