Repository kyma-project/istio, pull requests merged in 2024-02, with the labels that each got.

#600 Update action.yaml
  .github/actions/wait-for-job-succeed-or-fail/action.yaml
Labels: lgtm, size/XS, cla: yes

#601 Cherrypick a0ad780b83c3c713012331ba7e2924573b9f44f7
  .github/actions/wait-for-job-succeed-or-fail/action.yaml
  .github/workflows/pull-integration-gardener.yaml
Labels: size/S, lgtm, cla: yes

#605 Update the notes' style
  docs/user/00-10-overview-istio-controller.md
  docs/user/00-20-overview-service-mesh.md
  docs/user/operation-guides/02-20-enable-sidecar-injection.md
  docs/user/operation-guides/02-30-enable-istio-access-logs.md
  docs/user/tutorials/01-00-x-forwarded-for-header.md
Labels: size/S, lgtm, cla: yes

#607 Ignore sec-scanners-config.yaml for PR Integration Gardener workflow
  .github/workflows/pull-integration-gardener.yaml
Labels: lgtm, size/XS, cla: yes

#606 Update istio-manager version for security scanners
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#612 Add release notes for consistent labeling
  docs/release-notes/1.4.0.md
Labels: kind/feature, area/documentation, lgtm, size/XS, cla: yes

#614 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#617 Remove kyma-gateway from controlled resources list
  manifests/controlled_resources_list.yaml
Labels: lgtm, size/XS, cla: yes

#618 Remove not needed configmaps reconciliation leftovers
  internal/reconciliations/istio_resources/configmap_control_plane.go
  internal/reconciliations/istio_resources/configmap_control_plane_test.go
  internal/reconciliations/istio_resources/configmap_mesh.go
  internal/reconciliations/istio_resources/configmap_mesh_test.go
  internal/reconciliations/istio_resources/configmap_performance.go
  internal/reconciliations/istio_resources/configmap_performance_test.go
  internal/reconciliations/istio_resources/configmap_service.go
  internal/reconciliations/istio_resources/configmap_service_test.go
  internal/reconciliations/istio_resources/configmap_workload.go
  internal/reconciliations/istio_resources/configmap_workload_test.go
  internal/reconciliations/istio_resources/reconciliation.go
  tests/integration/features/istio/production/main-suite/istio_resources.feature
Labels: size/XL, lgtm, cla: yes

#616 Add conditions to Istio CR UI
  .gitignore
  config/ui-extensions/istios/details
Labels: lgtm, size/M, cla: yes

#622 Update action version and simplify istio CR details UI
  .github/actions/integration-test/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/upgrade-integration-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/performance-test.yaml
  .github/workflows/pull-integration-gardener.yaml
  .github/workflows/ui-tests.yaml
  config/ui-extensions/istios/details
Labels: lgtm, size/M, cla: yes

#625 Update DoD to include new item about Istio operator changes
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, size/XS, cla: yes

#621 Cherry-pick Istio 1.20.3
  VERSION
  controllers/istio_controller.go
  docs/release-notes/1.3.1.md
  go.mod
  go.sum
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#620 Istio 1.20.3
  controllers/istio_controller.go
  docs/release-notes/1.3.1.md
  go.mod
  go.sum
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#627 Change upgrade test to not merge manifest with old one
  tests/integration/features/istio/production/upgrade-suite/istio_upgrade.feature
  tests/integration/manifests/fail-operator-manifest.yaml
  tests/integration/scenario.go
  tests/integration/steps/operator.go
Labels: lgtm, size/L, cla: yes

#632 Set state to warning when more than one Istio CR is defined
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  tests/integration/features/istio/production/main-suite/istio_installation.feature
Labels: lgtm, size/XS, cla: yes

#633 Retrigger post pipelines
  internal/resources/apply.go
Labels: lgtm, size/XS, cla: yes

#635 Update manager image in sec-scanners-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#636 Update the docs related to Warning state on duplicate Istio CRs
  docs/contributor/04-10-technical-design.md
  docs/release-notes/1.4.0.md
  docs/user/00-10-overview-istio-controller.md
  docs/user/04-00-istio-custom-resource.md
Labels: lgtm, size/XS, cla: yes

#637 Add rc-tag for Release 1.3.1
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#638 Add Istio Update issue template
  .github/ISSUE_TEMPLATE/istio_update.md
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#643 Use 'in a cluster' instead of 'on a cluster'
  docs/contributor/04-10-technical-design.md
  docs/release-notes/1.4.0.md
  docs/user/00-50-resource-configuration.md
  docs/user/troubleshooting/03-50-recovering-from-unintentional-istio-removal.md
  hack/managed-kyma-migration/readme.md
Labels: size/S, lgtm, cla: yes

#644 Fix a broken link
  .github/ISSUE_TEMPLATE/istio_update.md
Labels: lgtm, size/XS, cla: yes

#647 docs: Enable access logs for the whole mesh and verify the telemetry resource
  docs/user/operation-guides/02-30-enable-istio-access-logs.md
Labels: kind/feature, area/documentation, lgtm, cla: yes

#645 Add an user tutorial about setting up an external authorizer
  docs/user/tutorials/01-10-external-authorization-provider.md
Labels: lgtm, size/L, cla: yes

#648 Update UI tests to work with latest Busola version
  tests/ui/cypress.config.js
  tests/ui/scripts/k3d-ci-kyma-dashboard-integration.sh
  tests/ui/support/buttons.js
  tests/ui/support/filter.js
  tests/ui/support/index.js
  tests/ui/support/lists.js
  tests/ui/support/login.js
  tests/ui/support/navigation.js
  tests/ui/support/views/namespace.js
  tests/ui/support/views/service.js
  tests/ui/tests/authorization-policies/test-authorization-policies.spec.js
  tests/ui/tests/destination-rules/test-destination-rules.spec.js
  tests/ui/tests/gateway/test-gateways.spec.js
  tests/ui/tests/istio/test-virtual-services.spec.js
  tests/ui/tests/service-entries/test-service-entries.spec.js
  tests/ui/tests/sidecars/test-sidecars.spec.js
Labels: lgtm, size/L, cla: yes

#615 Remove DNS handling from istio
  docs/release-notes/1.3.2.md
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/clusterconfig/gardener_shoot_info.go
  internal/reconciliations/istio_resources/reconciliation.go
  internal/reconciliations/istio_resources/reconciliation_test.go
  manifests/istio-operator-template-light.yaml
  manifests/istio-operator-template.yaml
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/scenario.go
  tests/integration/steps/istio.go
  tests/integration/testsupport/gardener.go
Labels: lgtm, size/L, cla: yes

#650 Update VERSION and sec-scanners-config files plus remove DNS handling
  VERSION
  docs/release-notes/1.3.2.md
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/clusterconfig/gardener_shoot_info.go
  internal/reconciliations/istio_resources/reconciliation.go
  internal/reconciliations/istio_resources/reconciliation_test.go
  manifests/istio-operator-template-light.yaml
  manifests/istio-operator-template.yaml
  sec-scanners-config.yaml
  tests/integration/features/istio/production/main-suite/istio_installation.feature
  tests/integration/scenario.go
  tests/integration/steps/istio.go
  tests/integration/testsupport/gardener.go
Labels: lgtm, size/L, cla: yes
