Repository kyma-project/istio, pull requests merged in 2025-01, with the labels that each got.

#1227 Print Istio CR in failed tests
  tests/integration/hooks.go
  tests/integration/scenario.go
Labels: size/S, lgtm, cla: yes

#1229 Update Istio version to 1.24.2
  README.md
  docs/release-notes/1.13.1.md
  docs/user/README.md
  go.mod
  go.sum
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#1239 Use head ref for release PR as base
  .github/workflows/call-unit-lint-head-ref.yaml
  .github/workflows/release-pr.yaml
Labels: lgtm, size/M, cla: yes

#1256 Add additional info to the failed run slack notification
  .github/actions/slack-notification-failed-workflow/action.yaml
Labels: lgtm, size/XS, cla: yes

#1257 Cleanup ci-cd docs
  docs/contributor/04-30-ci-cd.md
Labels: lgtm, size/M, cla: yes

#1259 Tutorial for Egress
  docs/user/tutorials/01-50-send-requests-using-egress.md
Labels: lgtm, size/L, cla: yes

#1243 Update information on Istio version
  README.md
  docs/assets/istio-whitelogo-bluebackground-framed.svg
  docs/user/00-10-compatibility-mode.md
  docs/user/00-10-istio-version.md
  docs/user/README.md
Labels: lgtm, size/M, cla: yes

#1266 Rename a file
  docs/user/00-10-istio-version.md
Labels: lgtm, size/XS, cla: yes

#1268 Update the Incompatible Istio Sidecars troubleshooting guide
  docs/user/troubleshooting/03-40-incompatible-istio-sidecar-version.md
  internal/restarter/sidecars.go
Labels: lgtm, size/M, cla: yes

#1267 Adjust post workflow to the new test strategy
  .github/actions/e2e-test-gardener/action.yaml
  .github/actions/e2e-test-k3d/action.yaml
  .github/actions/upgrade-integration-test/action.yaml
  .github/workflows/main-integration.yaml
  .github/workflows/post-main-workflow.yaml
  hack/ci/scripts-v2/deprovision-gardener.sh
  hack/ci/scripts-v2/gardener_kubeconfig.sh
  hack/ci/scripts-v2/integration-test-gardener.sh
  hack/ci/scripts-v2/provision-gardener.sh
  hack/ci/scripts-v2/set-aws-gardener.sh
  hack/ci/scripts-v2/set-gcp-gardener.sh
  hack/ci/scripts-v2/shoot_aws.yaml
  hack/ci/scripts-v2/shoot_gcp.yaml
Labels: size/XXL, lgtm, cla: yes

#1253 Refactor proxy reset
  controllers/istio_controller.go
  controllers/istio_controller_test.go
  docs/contributor/04-10-technical-design.md
  docs/release-notes/1.14.0.md
  internal/reconciliations/istio/configuration/configuration.go
  internal/reconciliations/istio/configuration/configuration_test.go
  internal/reconciliations/istio/configuration_test.go
  internal/reconciliations/istio/install.go
  internal/reconciliations/istio/uninstall.go
  internal/restarter/ingress_gateway.go
  internal/restarter/ingress_gateway_test.go
  internal/restarter/predicates/compatibility.go
  internal/restarter/predicates/compatibility_test.go
  internal/restarter/predicates/customer_workload.go
  internal/restarter/predicates/customer_workload_test.go
  internal/restarter/predicates/image_resources.go
  internal/restarter/predicates/image_resources_test.go
  internal/restarter/predicates/ingressgateway.go
  internal/restarter/predicates/ingressgateway_test.go
  internal/restarter/predicates/kyma_workload.go
  internal/restarter/predicates/kyma_workload_test.go
  internal/restarter/predicates/predicate.go
  internal/restarter/predicates/suite_test.go
  internal/restarter/sidecars.go
  internal/restarter/sidecars_test.go
  pkg/lib/sidecars/pods/filter_test.go
  pkg/lib/sidecars/pods/get.go
  pkg/lib/sidecars/pods/get_test.go
  pkg/lib/sidecars/proxy.go
  pkg/lib/sidecars/proxy_test.go
  pkg/lib/sidecars/remove/remove.go
  pkg/lib/sidecars/remove/remove_test.go
  pkg/lib/sidecars/restart/replica_set_action.go
  pkg/lib/sidecars/restart/restart.go
  pkg/lib/sidecars/restart/restart_factory.go
  pkg/lib/sidecars/restart/restart_test.go
  pkg/lib/sidecars/restart/rollout_action.go
  pkg/lib/sidecars/test/cases.go
  pkg/lib/sidecars/test/helpers/helpers.go
  pkg/lib/sidecars/test/pod_states.go
Labels: size/XXL, lgtm, cla: yes
