Repository kyma-project/istio, pull requests merged in 2025-03, with the labels that each got.

#1321 chore: update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm

#1325 Fix link to Istio 1.24.1 release
  docs/release-notes/1.11.0.md
Labels: lgtm, size/XS

#1326 Fix missing permissions for image-builder
  .github/workflows/release-create-release.yaml
  .github/workflows/release-pr.yaml
  .github/workflows/schedule-performance-test.yaml
  .github/workflows/schedule-ui-tests-periodic.yaml
Labels: size/S, lgtm

#1327 Fix missing permissions for image-builder (#1326)
  .github/workflows/release-create-release.yaml
  .github/workflows/release-pr.yaml
  .github/workflows/schedule-performance-test.yaml
  .github/workflows/schedule-ui-tests-periodic.yaml
Labels: size/S, lgtm

#1328 Add missing permission for image-builder
  .github/workflows/post-main-workflow.yaml
  .github/workflows/release-create-release.yaml
  .github/workflows/release-pr.yaml
  .github/workflows/schedule-performance-test.yaml
  .github/workflows/schedule-ui-tests-periodic.yaml
Labels: size/S, lgtm

#1330 Cherry pick - add missing permission for release
  .github/workflows/post-main-workflow.yaml
  .github/workflows/release-create-release.yaml
  .github/workflows/release-pr.yaml
  .github/workflows/schedule-performance-test.yaml
  .github/workflows/schedule-ui-tests-periodic.yaml
Labels: size/S, lgtm

#1332 Ensure linter version to mitigate breaking changes on rel branch
  .github/workflows/call-unit-lint.yaml
Labels: lgtm, size/XS

#1333 Ensure lint version to avoid breaking changes
  .github/workflows/call-unit-lint-head-ref.yaml
Labels: lgtm, size/XS

#1232 feat: Enable prometheus merge as a configuration in the Kyma Istio CR
  api/v1alpha2/istio_merge.go
  api/v1alpha2/istio_structs.go
  api/v1alpha2/merge_test.go
  api/v1alpha2/telemetry.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_istios.yaml
  config/ui-extensions/istios/details
  config/ui-extensions/istios/form
  config/ui-extensions/istios/translations
  controllers/istio_controller_test.go
  docs/contributor/adr/0010-support-for-enable-prometheusMerge-configuration.md
  docs/release-notes/1.15.0.md
  docs/user/04-00-istio-custom-resource.md
  internal/reconciliations/istio/configuration/configuration_test.go
  internal/restarter/predicates/prometheus_merge.go
  internal/restarter/predicates/prometheus_merge_test.go
  pkg/lib/sidecars/proxy.go
  pkg/lib/sidecars/proxy_test.go
Labels: lgtm, size/L, cla: yes

#1335 Istio release 1.15 security config
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#1338 Fix e2e test in the rel workflow
  .github/workflows/call-integration-tests.yaml
Labels: lgtm, size/M

#1314 Create GH workflow.
  .github/actions/get-latest-sha/action.yaml
  .github/actions/k8s-compatibility-test-aws/action.yaml
  .github/actions/k8s-compatibility-test/action.yaml
  .github/actions/perf-test-gardener/action.yaml
  .github/workflows/schedule-main-integration.yaml
  .github/workflows/schedule-performance-test.yaml
  .github/workflows/schedule-ui-tests-periodic.yaml
  Makefile
  hack/ci/gardener-perf-test.sh
  hack/ci/scripts-v2/performance-test-gardener.sh
  tests/performance/Makefile
Labels: size/XL, cla: yes

#1317 feat: Conditional switch to NLB load balancer
  controllers/elb_config_map_predicate.go
  controllers/istio_controller.go
  docs/user/tutorials/01-60-enable-nlb-load-balancer.md
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/reconciliations/istio_resources/proxy_protocol_envoy_filter.go
  internal/reconciliations/istio_resources/proxy_protocol_envoy_filter_test.go
  internal/reconciliations/istio_resources/reconciliation.go
  internal/reconciliations/istio_resources/reconciliation_test.go
  internal/resources/resources.go
Labels: size/L, cla: yes, do-not-merge/hold
