Repository kyma-project/istio, pull requests merged in 2025-02, with the labels that each got.

#1273 release: update security scanner config and version file
  VERSION
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1274 Fix release workflow yq
  .github/workflows/release-create-release.yaml
Labels: size/S, lgtm, cla: yes

#1275 Fix release workflow yq (#1274)
  .github/workflows/release-create-release.yaml
Labels: size/S, lgtm, cla: yes

#1276 Update dependabot to release-1.14 branch
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1278 Set global metrics rotation interval to 6h
  docs/release-notes/1.13.2.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
Labels: size/S, lgtm, cla: yes

#1283 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/istio_update.md
Labels: lgtm, size/M, cla: yes

#1291 chore: remove yq from release-create-release.yaml
  .github/workflows/release-create-release.yaml
  Makefile
Labels: lgtm, size/M, cla: yes

#1290 Rel 1.13.2
  VERSION
  docs/release-notes/1.13.2.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm, cla: yes

#1296 Release 1.14.1
  .github/workflows/release-create-release.yaml
  Makefile
  VERSION
  docs/release-notes/1.13.2.md
  docs/release-notes/1.14.1.md
  internal/istiooperator/istio-operator-light.yaml
  internal/istiooperator/istio-operator.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/M, cla: yes

#1294 Adjust PR workflow to the new test strategy
  .github/workflows/call-pull-e2e.yaml
  .github/workflows/pull-build-push.yaml
  .github/workflows/pull-integration-gardener.yaml
  .github/workflows/pull-request.yaml
Labels: lgtm, size/L, cla: yes

#1297 Bump k8s version in compatibility test
  .github/actions/k8s-compatibility-test/action.yaml
Labels: lgtm, size/XS, cla: yes

#1286 Add tutorial for egress with mTLS
  docs/user/tutorials/01-50-send-requests-using-egress.md
  docs/user/tutorials/01-55-send-requests-using-egress-and-mtls.md
  pkg/lib/gatherer/gatherer.go
  tests/integration/steps/deployment.go
Labels: lgtm, size/L, cla: yes

#1305 bug: increase backoff on e2e test
  Makefile
  tests/e2e/egress/egress_test.go
Labels: lgtm, size/XS, cla: yes

#1308 add tutorials to sidebar
  docs/user/_sidebar.md
Labels: lgtm, size/XS, cla: yes

#1311 Fix broken links in the sidebar
  docs/user/_sidebar.md
Labels: lgtm, size/XS, cla: yes

#1303 ADR for Processing status handling of Istio module
  docs/contributor/adr/0010-module-status.md
Labels: lgtm, size/M, cla: yes

#1310 bug: remove test-e2e from GCP integration tests
  .github/workflows/call-integration-tests.yaml
Labels: lgtm, size/XS, cla: yes

#1312 bug: remove test-e2e from GCP integration tests 2
  .github/workflows/post-main-workflow.yaml
Labels: lgtm, size/XS, cla: yes

#1315 docs: Explain access logs filtering
  docs/user/tutorials/01-45-enable-istio-access-logs.md
Labels: size/S, lgtm, cla: yes
